### ISSUE TITLE
[P1][Sourcing] Perf issue when table has multiple components in `virtualScroll`

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10339] opened 2023-08-14 05:14 UTC
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In platform table with `virtualScroll` enabled, we have at least two different NGX components in table rows. Scrolling pass `renderAhead` will easily cause whitespace and some delays.

https://github.com/SAP/fundamental-ngx/assets/22842279/d6405f9c-6776-4404-8a31-4284a9c67c86

And sometimes the table will slowly jump up (from 0:08):

https://github.com/SAP/fundamental-ngx/assets/22842279/c6c9bac1-1313-45ff-ba71-a8f9097b7778

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.43.0

#### If this is a bug, please provide steps for reproducing it.

- Create a platform table with different NGX components in table rows (2 should be enough to reproduce the issue)
- Scrolling pass `renderAhead` and keep scrolling.
- For jumping issue, it sometimes happens after whitespace or we scroll up.

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-8z3jzr-xt1ve6?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html

**Comment by fkolar** [comment] 2023-08-29 14:03
I think this is duplicate of some other issue @CSENoni, you can link this issue in here: https://github.com/SAP/fundamental-ngx/issues/10321.


Should we manage this as one ? I think this is the same no?

**Comment by CSENoni** [comment] 2023-08-29 14:43
@fkolar checking, I will give more details, but the scenario in this one is different. First guess is that because we have different components in each row here, scroll will create new component instead of component reuse with state changed. I will create another stackblitz to better showcase this issue if possible.

**Comment by fkolar** [comment] 2023-08-29 14:49
Right, this is more performance, where the other is strange scrolling behavior..

**Comment by CSENoni** [comment] 2023-08-29 17:10
I created two customized components with lifecyle hooks to see how it is behaved: https://stackblitz.com/edit/angular-8z3jzr-uw3zn4?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html

https://github.com/SAP/fundamental-ngx/assets/22842279/a3bbe759-e44c-452a-9d44-47eba7f98807

It looks like each scroll, component in each row will run through `ngOnChange`, `ngOnInit`, `ngOnDestroyed` in the opposite to a single component when only `ngOnChange` is executed: https://stackblitz.com/edit/angular-8z3jzr-ueptwn?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html

https://github.com/SAP/fundamental-ngx/assets/22842279/8038c381-e335-481a-8c26-2b794295ae15

So, in this scenario, we basically create a new component for every visible row (with maybe renderAhead) when scrolling.

Yes @fkolar, this scenario is about perf issue.

**Comment by N1XUS** [comment] 2023-08-31 09:38
The issue with the example from this ticket is that you render components conditionally. So, on each scroll (let's assume we scroll over 200 lines per one scroll event), angular needs to recalculate the condition for over 200 rows (4 conditions per row and 2 components per row), in the end we have 400 components that needs to be re-initialized completely (not reuse existing component, but create a new one) in one scroll event. This generates a bottleneck in task pool that turns to be the issue you've experienced on the video.

In your case I think easiest thing to do would be to keep both components initialized per cell, but hide them with conditional styling. This will save some initialization and calculation time, yet may drain memory a bit more.

As stated many times, virtual scroll is a good technique to deal with large amount of **data**, and not dynamically rendered **components**.

**Closed by N1XUS** 2023-08-31 09:38 UTC

**Comment by CSENoni** [comment] 2023-09-04 07:36
The workaround (use style to hide component) works but side effect (memory usage) may or may not be the issue depending on how many different types we have on table as we only have 2 in the example. The perf degradation can also be seen in angular cdk, so it should be handled by our side by either this workaround or design changed. Thanks!
