### ISSUE TITLE
Positioning of the `description` in `fd-grid-list-item`

### ISSUE THREAD

**Issue by I539321** [SAP/fundamental-ngx#10035] opened 2023-06-14 22:41 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

Unsure if this has been reported before, but it seems that in the `fd-grid-list-item` the “description” appears below the avatar line, I believe this might be something that can be improved. I’m attaching here a screenshot of this. Let me know if more clarity is needed.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

I guess it happens on version 0.41.0 of the Fundamental library, and Angular 15.

#### If this is a bug, please provide steps for reproducing it.

Simply iterate a `fd-grid-list-item` within a `fd-grid-list`.

![Screenshot 2023-06-06 at 13 27 28](https://github.com/SAP/fundamental-ngx/assets/101869667/7fb545c2-dcff-45de-b949-1e644d8577f3)

**Comment by droshev** [comment] 2024-08-02 23:55
@khotcholava Can you check that issue while doing the keyboard support too? Thanks

**Comment by khotcholava** [comment] 2024-08-05 08:32
@I539321 Please provide stackblitz example.

**Comment by khotcholava** [comment] 2024-08-05 11:31
@droshev This issue has been fixed in the latest version of `fundamental-ngx`.

**Comment by SAPAndiBraimllari** [comment] 2024-08-05 12:52
Thanks for your updates, I'll double check it once we upgrade and then decide to close this or not. Thanks again!

**Comment by khotcholava** [comment] 2024-08-05 13:22
@SAPAndiBraimllari No problem!

**Comment by droshev** [comment] 2024-08-05 14:29
@SAPAndiBraimllari you can open a new ticket if the issue is still there.

**Closed by droshev** 2024-08-05 14:29 UTC
Labels: design
