### ISSUE TITLE
bug: list(platform) - incorrect work of radio button

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#7303] opened 2021-12-02 12:54 UTC
#### Is this a bug, enhancement, or feature request?
**Bug**

#### Briefly describe your proposal.
Unable to select radio button 

#### If this is a bug, please provide steps for reproducing it.

1. Go to https://fundamental-ngx.netlify.app/#/platform/list#single-selection
2. Click any radio button
**Actual result:**
![image](https://user-images.githubusercontent.com/74654139/144425484-1542dbd0-d0ad-4df3-aea6-ead8bbac6d44.png)
**Expected result:**
![image](https://user-images.githubusercontent.com/74654139/144425733-d9a2ffe2-4c0f-46e3-ab83-d5e0c726a087.png)

**Comment by maxym-valor** [comment] 2021-12-02 13:50
Duplicate of https://github.com/SAP/fundamental-ngx/issues/7245

**Closed by maxym-valor** 2021-12-02 13:50 UTC
Labels: bug, platform
