### ISSUE TITLE
Bug: Components within Dialog does not exhibit RTL

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5841] opened 2021-06-28 23:40 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Components within Dialog does not exhibit RTL. Examples below.
<img width="604" alt="Template Based Dialog" src="https://user-images.githubusercontent.com/71797052/123716119-ac8dc700-d82e-11eb-828c-f693c7410b6b.png">
<img width="624" alt="Component Based Dialog" src="https://user-images.githubusercontent.com/71797052/123716132-b3b4d500-d82e-11eb-8dfd-e34822598551.png">

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/dialog
Scroll and click through all of the components
See error. (Only Custom Backdrop and Container) - gets it correct

**Comment by N1XUS** [comment] 2021-07-09 08:54
Duplicate of #5792

**Closed** 2021-07-09 11:10 UTC
Labels: denoland-porto, documentation
