### ISSUE TITLE
Observable Async - Multi Input field value is not displayed properly

### ISSUE THREAD

**Issue by saurabhagarwal7755** [SAP/fundamental-ngx#12103] opened 2024-07-12 09:36 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
In Observable Async - Multi Input field,

on searching for an option by typing in keyboard the value appears in the drop down and after selection, the selected option is shown as well as the text I searched is also shown in the multi-input field. Only the selection option should be shown in this case.
![image](https://github.com/user-attachments/assets/bab3b209-6027-402e-9ea7-a99c76e2f450)

on searching for an option by typing in keyboard the value doesn't show properly, sometime I can see the valueFn content is shown in the field instead of displayFn content. Only the content in the displayFn should be shown.
![image](https://github.com/user-attachments/assets/58bfd5e1-e875-482b-b941-b96d4835c55c)

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.46.0-rc5 onwards

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
https://fundamental-ngx.netlify.app/#/core/multi-input#observable-async
Use keyboard for searching the options.

#### Please provide relevant source code (if applicable).
https://fundamental-ngx.netlify.app/#/core/multi-input#observable-async

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by khotcholava** [comment] 2024-07-22 10:30
@saurabhagarwal7755 Hello, could you please provide more detailed steps on how to reproduce this issue? I haven't been able to replicate it.

**Comment by khotcholava** [comment] 2024-09-19 12:02
@saurabhagarwal7755 Ping

**Comment by droshev** [comment] 2024-09-19 13:11
@saurabhagarwal7755 Is it possible to provide more details as @khotcholava asked? If the issue is not reproducible we can close it.

**Comment by droshev** [comment] 2024-09-27 00:19
@saurabhagarwal7755 closing the issue as there is not updates. Feel free to open a new issue if it is reproducible and answer @khotcholava 's questions. thanks

**Closed by droshev** 2024-09-27 00:19 UTC
