### ISSUE TITLE
Select: Able to see the fdp option in the selected item

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4595] opened 2021-02-08 07:10 UTC
Description: Able to see the fdp option in the selected item

Expected: Should not the fdp option in the selected item

Screenshot attached 

![image](https://user-images.githubusercontent.com/32538291/107186719-ca3acb00-6a0a-11eb-9961-dd4cf7eda7f5.png)

**Comment by sKudum** [comment] 2021-02-08 08:41
HI @puru-hk , As mentioned in documentation part, it is reference  we are displaying along with selected item.  Hence closing. it as it is not a bug.

**Closed by sKudum** 2021-02-08 08:41 UTC
Labels: Defect Hunting, Medium, bug, core
