### ISSUE TITLE
[P3][Sourcing][Need Input] Adding styles to particular cells in fdp-table not possible.

### ISSUE THREAD

**Issue by Sayandeep-123** [SAP/fundamental-ngx#11898] opened 2024-05-08 06:16 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
Adding styles (colors) to the particular cells( for example, cell corresponding to column 2 and row 2) are not possible.
These styles should be added based on some condition or action.

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
F-NGX - v0.43.34
Angular - ng15

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Component used - fdp-table
Adding styles (colors) to the particular cells( for example, cell corresponding to column 2 and row 2) are not possible.
These styles should be added based on some condition or action.

#### Did you check the documentation and the API?
Yes, couldn't find any info related to it.

#### Did you search for similar issues?
Yes, couldn't find any issue similar to it.

#### Is there anything else we should know?
No

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by droshev** [comment] 2024-05-09 14:09
this requirement needs to be validated by designers, reflect theming, and accessiblity.

**Comment by droshev** [comment] 2024-05-23 19:07
closing as it needs to go through a proper design process

**Closed by droshev** 2024-05-23 19:07 UTC
