### ISSUE TITLE
Bug: Carousel: Button is getting misplaced while trying to navigate to next item

### ISSUE THREAD

**Issue by manjunathanagaraj** [SAP/fundamental-ngx#3988] opened 2020-12-02 02:30 UTC
#### Is this a bug, enhancement, or feature request?
This is a bug

#### Briefly describe your proposal.
1. Go to carousel documentation example(https://fundamental-ngx.netlify.app/#/core/carousel).
2. In the "Carousel with navigation inside content area" example, try to click on the navigation button to view next item(click on '>' button).
3. The navigation button moves to the top left corner, navigation action is not performed. But navigation happens if i click on the navigation button which is placed at the top left corner.
4. Try to navigate to previous item by clicking on '<' button. Same buggy behaviour is seen.

Tested on Mac/Chrome

**Comment by DeepakSap14** [comment] 2020-12-02 03:47
This will be fixed with https://github.com/SAP/fundamental-styles/pull/1928.

**Comment by DeepakSap14** [comment] 2020-12-02 03:48
Issue present in fundamental-style for this fix.
https://github.com/SAP/fundamental-styles/issues/1927

This issue is duplicate of https://github.com/SAP/fundamental-styles/issues/1927. so this can be closed.

**Closed by DeepakSap14** 2020-12-02 03:48 UTC
