### ISSUE TITLE
Accessibility Bug: This A element has an accessible name of 'breadcrumb level 3' that is not unique.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3153] opened 2020-08-30 05:17 UTC
Fundamental core component: "Breadcrumbs"

Description: This A element has an accessible name of 'breadcrumb level 3' that is not unique.

Code Snippet:
a href="#/core/breadcrumb/%23?0=%23" class="fd-breadcrumb__link" fd-breadcrumb-link="" _ngcontent-whp-c472="">Breadcrumb Level 3</a>

Expected: Ensure the accessible name of each link accurately reflects the target and purpose of the link when the link and its surrounding text is taken into context.

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651770-36a1bd80-eaae-11ea-8af6-e072cf563b86.png)

**Comment by Sanjay-1312** [comment] 2021-06-01 05:13
Hello Colleagues,

The issue is fixed.
Hence  closing the ticket.

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-06-01 05:13 UTC
Labels: ATL, Medium, QA Approved, bug, core
