### ISSUE TITLE
[Sourcing][WIP][P1] Page becomes unresponsive when using value-help-dialog component

### ISSUE THREAD

**Issue by sahanaN123** [SAP/fundamental-ngx#11161] opened 2024-01-01 05:49 UTC
#### Is this a bug, enhancement, or feature request?
Yes, its a BUG where page becomes unresponsive when value-help-dialog component is active in application where we have large set of data. Also this is happening after the version 0.43.22.

#### Can you handle that on the application side
No 

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.43.22

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
value-help-dialog with advanced filters in it.

#### Please provide stackblitz example(s).
we were not able to replicate in stackblitz as we did not have much data there. 

https://stackblitz.com/edit/angular-ugca8x-tigsbs?file=src%2Fapp%2Fdynamic-page-tabs-example.component.html,src%2Fapp%2Fdynamic-page-tabs-example.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by N1XUS** [comment] 2024-01-02 11:09
Relates to #11163

**Comment by N1XUS** [comment] 2024-01-02 15:32
@sahanaN123 Hello. I've tried with 13700 items, and it works fine: https://stackblitz.com/edit/angular-ugca8x-4wwsbx?file=src%2Fapp%2Fdynamic-page-tabs-example.component.html,src%2Fapp%2Fdynamic-page-tabs-example.component.ts,node_modules%2F%40fundamental-ngx%2Fplatform%2Fvalue-help-dialog%2Fmodels%2Fvhd-data.source.d.ts

Can you elaborate more on what's may cause such issue with unresponsive window? How much entries to you render at once? How do you apply filtering (is it backend or frontend)?

**Comment by sahanaN123** [comment] 2024-01-12 14:41
@N1XUS : I will re-check and come back with the confirmation. Thanks

**Comment by sahanaN123** [comment] 2024-01-16 04:48
@N1XUS : we tested it again on our application and find it to be working fine for now. but we would expect that enhancement of migration core table to platform table in value-help-dialog component.

**Comment by N1XUS** [comment] 2024-01-16 09:03
I'm closing this issue for now since it's not reproducible anymore.

**Closed by N1XUS** 2024-01-16 09:03 UTC
Labels: enhancement
