### ISSUE TITLE
The accessibility for menu dropdown in ngx seems not correct

### ISSUE THREAD

**Issue by wei368** [SAP/fundamental-ngx#7972] opened 2022-04-08 17:55 UTC
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.

In NGX https://sap.github.io/fundamental-ngx/#/core/menu, the first menu item will have dotted box when we click the dropdown menu.

https://user-images.githubusercontent.com/5350405/162496584-396dc1ca-bfa6-426a-a0bd-1502ba3a26b2.mov

 But in most other applications, for example like this (https://a11y-guidelines.orange.com/en/web/components-examples/dropdown-menu/), they did not have box for the first menu item until a user mouse over or tab to the first menu item. 

https://user-images.githubusercontent.com/5350405/162497134-da8993f3-8f5c-446d-bfdb-1224d62c8d73.mov

Should we change the accessibility to most of other website do, or keep what current NGX specific accessibility for menu?

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
NGX 32, Angular version 12

**Comment by wei368** [comment] 2022-05-16 17:02
Hi: any update on this issue?

**Comment by mikerodonnell89** [comment] 2022-06-06 16:59
This is by design - closing the menu with escape will re-focus the menu button

**Comment by mikerodonnell89** [comment] 2022-09-02 19:53
@wei368 closing this issue as it is behaving as intended. This is conforming with the w3c standard: https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-links

**Closed by mikerodonnell89** 2022-09-02 19:53 UTC
