### ISSUE TITLE
Bug:  Core Card counter is displaying wrong information in RTL mode

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#4736] opened 2021-02-22 08:02 UTC
#### Is this a bug, enhancement, or feature request?

Bug
#### Briefly describe your proposal.

Bug: Fd card counter is displaying wrong information in RTL mode.

on the RTL mode the value printed is in the Illegible format, counter is displayed as  'of 10 3' instead of '3 of 10'

#### If this is a bug, please provide steps for reproducing it.

Step1 : Open URL (https://fundamental-ngx.netlify.app/#/core/card)
Step2: Switch to simulate to RTL mode.
Step 3: string in the counter is in 'of 10 3' instead of '3 of 10'

Screen shot:
<img width="1141" alt="Screenshot 2021-02-22 at 1 09 25 PM" src="https://user-images.githubusercontent.com/53534379/108679127-13624300-7512-11eb-8168-2154533cb842.png">

**Comment by DeepakSap14** [comment] 2021-02-22 09:04
duplicate of #3418
https://github.com/SAP/fundamental-ngx/issues/3418

**Comment by olshansky** [comment] 2021-02-22 13:49
@Lokanathan-k as discussed in https://github.com/SAP/fundamental-ngx/issues/3418 it's not the library issue, it's native behavior of the browser. Take a look at [this comment](https://github.com/SAP/fundamental-ngx/issues/3418#issuecomment-700573734).

**Closed** 2021-03-29 06:51 UTC
Labels: Defect Hunting, Low, bug, duplicate
