### ISSUE TITLE
bug: wizard-generator(platform): steps switching by scrolling do not work for 2 examples

### ISSUE THREAD

**Issue by maxym-valor** [SAP/fundamental-ngx#7046] opened 2021-10-29 11:43 UTC
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
Steps switching by scrolling: when you scroll between steps - on header should change highliting steps, i.e. you see element of 1 step - first step should be highlited as current
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.33.0
OS: Windows 10
Browser: FF 93
#### If this is a bug, please provide steps for reproducing it.
1. Open https://fundamental-ngx.netlify.app/#/platform/wizard-generator
2. Scroll to ` Handling complex objects rendering on Summary page` example (or `Visible summary step in progress bar`)
3. Fill first step
4. Click 'next step'
5. Scroll to first step
Expected result: first step highlited as current
Actual result: second step still  highlited as current
#### Is there anything else we should know?
https://user-images.githubusercontent.com/83698366/139428648-28541bea-6a9b-45d7-a0a4-07ee98ac1f6d.mp4
![image](https://user-images.githubusercontent.com/83698366/139428704-8c1db106-d265-4c28-b55d-e96b61ff09bd.png)

**Comment by dmitry-stepanenko** [comment] 2021-12-03 15:57
This issue is also replicatable on MacOS in Chrome on small resolution

Uploading Dec-03-2021 17-57-09.mp4…

**Comment by mikerodonnell89** [comment] 2022-10-10 16:38
Thank you for raising this issue. The scrolling logic depends on the wizard being a full-screen wizard, and we encourage you to use `[appendToWizard]="false"` otherwise. This needs to be more clearly documented. Another duplicate of this issue has been created so I am closing that one and this one, please follow #8823

**Closed by mikerodonnell89** 2022-10-10 16:38 UTC
Labels: bug, platform, E2E automation
