### ISSUE TITLE
input width issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3354] opened 2020-09-21 21:50 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
the width of the input gets truncated

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.

If we go to textarea page directly there is no issue:
https://fundamental-ngx.netlify.app/#/platform/input
there is no issue
![platform-input](https://user-images.githubusercontent.com/4380815/93825166-b563c380-fc32-11ea-9254-e2b22de325d5.gif)

how to reproduce the issue:
1. go to https://fundamental-ngx.netlify.app/#/platform/home
2. refresh the page
3. go to combobox https://fundamental-ngx.netlify.app/#/platform/combobox
4. go to https://fundamental-ngx.netlify.app/#/platform/input
![platform-input-issue](https://user-images.githubusercontent.com/4380815/93825232-d4faec00-fc32-11ea-8312-fbb8c0f8e271.gif)

**Comment by Lokanathan-k** [comment] 2020-09-30 13:15
On analysing the issue found that the issue is `fd-popover-custom` which is loaded from popover is cached and its overriding the fdp-form-input-message-group.component.scss  `fd-popover-custom` this issue will be fixed on fixing the issue https://github.com/SAP/fundamental-ngx/issues/3358 Combobox width issue.

**Comment by InnaAtanasova** [comment] 2020-10-01 16:50
Will be fixed in https://github.com/SAP/fundamental-ngx/issues/3413

**Closed by InnaAtanasova** 2020-10-01 16:50 UTC
Labels: 0.22.0, Defect Hunting, bug, platform
