### ISSUE TITLE
[P3.2][Sourcing][Accessibility][ATL testing][Table]: Space key not working on whole row focus for checkbox check / uncheck, screenreader reads use space key

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10619] opened 2023-09-29 06:02 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.

Space key not working on whole row focus for checkbox check / uncheck in a multi-select row table, though screenreader reads use space key but it doesnt work on space key press

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
ng: 15
platform: 0.43.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
multi-select platform table

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
reported by ATL team

**Comment by droshev** [comment] 2023-10-02 13:53
@I543348 Can you provide more information: e.g. which example from the documentation you were testing?

**Comment by I543348** [comment] 2023-10-03 14:38
Hi @sagar7259 pls help us with more info as it was captured during ATL testing.
Thanks.

**Comment by sagar7259** [comment] 2023-10-04 03:37
@droshev this issue was found with testing the multi value input within the application. On activating the help popover button, a dialog appears on the screen and this issue was found within this dialog.
![image](https://github.com/SAP/fundamental-ngx/assets/143692208/4e002563-24b0-444e-b566-b40bb8bc9aa7)

On accessing each table row, the tutor message "To select row press spacebar" is being read, but on using the spacebar nothing changes on the screen. 
Here to select a row first user should use F2 key to dive into each cell and navigate to the 'Check ox' of each row to select a row.

Here the either tutor message should be corrected or the right functionality should be provided.

Regards,
Sagar

**Comment by nikolay-kolarov** [comment] 2023-11-03 16:04
Hi @droshev,
Hi @InnaAtanasova,

I was able to reproduce this in the tree table here: https://ng-15-downport--fundamental-ngx.netlify.app/#/platform/table/basic
Since the tr element does not have an aria-label/aria-labelledby it reads all the cells that it contains -> and the first cell contains  a label to indicate that space needs to be pressed to activate the row.
So one option would be to contsruct a string with the value of the row and pass it to aria-labelledby. This is done on focus in the responsive table in UI5: https://ui5.sap.com/#/entity/sap.m.Table/sample/sap.m.sample.TableMultiSelectMode
The other option is to not allow the cell in the tree on whole row, like it is in the UI5 tree table: https://ui5.sap.com/#/entity/sap.ui.table.TreeTable/sample/sap.ui.table.sample.TreeTable.JSONTreeBinding

Best Regards,
Nikolay

**Comment by mikerodonnell89** [comment] 2024-01-04 18:01
Closing as this was moved to the individual cell:

https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/table/components/table-row/table-row.component.html#L43

**Closed by mikerodonnell89** 2024-01-04 18:01 UTC
Labels: ng15

**Comment by sagar7259** [comment] 2024-01-05 07:53
Hello Colleagues,

This issue is no more reproducible. Now the selection can only be done when the focus is on check box and spacebar key is working as expected. But there one issue where on selecting any row by checking the check box, the screen gets automatically scrolled done and this issue is handled in other ticket.
https://github.com/SAP/fundamental-ngx/issues/11130

Hence this ticket can be closed.

Regards,
Sagar
