### ISSUE TITLE
Bug: Input Group: Tooltip is not seen in RTL mode 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3319] opened 2020-09-17 05:42 UTC
Description: Tooltip is not seen in RTL mode 
Expected: Tooltip should be displayed properly in RTL mode 

Attached screenshot:

Isssue

![image](https://user-images.githubusercontent.com/32538291/93424899-971a6280-f8d6-11ea-91b0-8594724de4c4.png)

Normal mode

![image](https://user-images.githubusercontent.com/32538291/93424924-ab5e5f80-f8d6-11ea-834f-b3ce53c4dd6a.png)

**Comment by dimamarksman** [comment] 2020-09-18 16:06
Seems it works so for anyone who uses `inline help` component.
Event with `fdp-input` it is not working as well
![image](https://user-images.githubusercontent.com/3263744/93619498-45aaca00-f9e1-11ea-801a-01917f3f1486.png)

So it's connected to the `inline-help` used by `form-field` component, not `fdp-input-group` itself.

@puru-hk  Let's change the issue title to highlight that it's connected to the form field inline help.

**Comment by kavya-b** [comment] 2021-05-07 05:44
This has probably been fixed in recent releases since it is not reproducible anymore, the tooltip/help is visible: 
![image](https://user-images.githubusercontent.com/53509521/117403058-31dab680-af25-11eb-809c-08f7c69c8efe.png)
Hence closing this issue.

cc: @manjunathanagaraj @puru-hk

**Closed by kavya-b** 2021-05-07 05:44 UTC
Labels: Medium, bug, platform
