### ISSUE TITLE
Select: Popup is not closing after add and remove option

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#4615] opened 2021-02-09 07:13 UTC
Description: Popup is not closing after add and remove option

Expected: Popup should closed when user click anywhere in the screen

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/107328230-667cd480-6ad4-11eb-9c5a-926262e53cd8.png)

**Comment by sKudum** [comment] 2021-02-09 07:19
Hi Puru,
 it is feature provided **closeonoutsideclick=false**  , by default it is true because of which other popups are getting closed.

it is not a bug hence closing it.

**Closed by sKudum** 2021-02-09 07:19 UTC
Labels: Medium, bug, core
