### ISSUE TITLE
Defect Hunting for Sprint 92

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#8342] opened 2022-07-11 13:50 UTC

**Comment by mikerodonnell89** [comment] 2022-07-11 16:30
- [ ] This should bring up a full-screen dialog menu. Buttons should also be cozy
<img width="468" alt="Screen Shot 2022-07-11 at 10 26 48 AM" src="https://user-images.githubusercontent.com/2471874/178312353-7d63fb92-b6af-4048-93e8-41e8d8e8bda8.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 18:36
- [ ] Alert - the alignment for the success alert is not correct
<img width="1370" alt="Screen Shot 2022-07-11 at 2 35 02 PM" src="https://user-images.githubusercontent.com/39598672/178334428-e3e78b95-f33d-45b8-bbac-17d450521da8.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 18:50
- [ ] Content density
When content density is changed to `condensed` the changes are applied to all elements (in this case it's Bar component). Condensed is only applied to Table.
<img width="1627" alt="Screen Shot 2022-07-11 at 2 47 26 PM" src="https://user-images.githubusercontent.com/39598672/178336358-37281778-8bb0-4553-b98b-a1a305339ce1.png">

**Comment by mikerodonnell89** [comment] 2022-07-11 18:54
> * [ ]  Content density
>   When content density is changed to `condensed` the changes are applied to all elements (in this case it's Bar component). Condensed is only applied to Table.

@InnaAtanasova The think the idea here is that condensed is the smallest of the 3 visually so it is assumed that if you want globally condensed visuals, you'll want compact not cozy for the components that do have a compact size but not condensed.

**Comment by InnaAtanasova** [comment] 2022-07-11 18:59
> > * [ ]   Content density
> >   When content density is changed to `condensed` the changes are applied to all elements (in this case it's Bar component). Condensed is only applied to Table.
> 
> @InnaAtanasova The think the idea here is that condensed is the smallest of the 3 visually so it is assumed that if you want globally condensed visuals, you'll want compact not cozy for the components that do have a compact size but not condensed.

I don't think so. Condensed is specific for Table and is not intended to be used separately. Here's a screenshot from the UX guidelines:
<img width="1208" alt="Screen Shot 2022-07-11 at 2 57 12 PM" src="https://user-images.githubusercontent.com/39598672/178338305-6e061a1c-4766-4143-bf15-7ed1ee0a667b.png">

And a link to the spec:
https://experience.sap.com/fiori-design-web/tree-table/

**Comment by InnaAtanasova** [comment] 2022-07-11 19:09
- [ ] Combobox as Search Field gets doubled focus for clear and search 
<img width="1195" alt="Screen Shot 2022-07-11 at 3 07 53 PM" src="https://user-images.githubusercontent.com/39598672/178339948-3f6c6bbd-035c-4ed5-9609-3b6e8f509b89.png">
<img width="1214" alt="Screen Shot 2022-07-11 at 3 07 48 PM" src="https://user-images.githubusercontent.com/39598672/178339950-21cc6c31-fb73-4e83-8a97-71bc3e1b1289.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 19:20
- [ ] Link - icon is underlined on focus state
<img width="443" alt="Screen Shot 2022-07-11 at 3 20 01 PM" src="https://user-images.githubusercontent.com/39598672/178341718-5be1e786-f5fb-4ef8-85bd-4000c12c55b2.png">
<img width="507" alt="Screen Shot 2022-07-11 at 3 20 06 PM" src="https://user-images.githubusercontent.com/39598672/178341721-6e069456-cb3b-4408-b933-9164757cf7b9.png">

**Comment by mikerodonnell89** [comment] 2022-07-11 19:35
- [ ] Horizon Breadcrumb menu item - focus border radius is not correct
rounded bottom corners on the breadcrumb:
<img width="189" alt="Screen Shot 2022-07-11 at 1 19 07 PM" src="https://user-images.githubusercontent.com/2471874/178341606-2d8489b6-b6ae-4dcb-896a-b66aad79d41f.png">
correct implementation on the menu:
<img width="116" alt="Screen Shot 2022-07-11 at 1 19 04 PM" src="https://user-images.githubusercontent.com/2471874/178341642-563b37f3-2999-4131-9e6b-9cf43a181f74.png">

- [ ] Full-screen mobile dialogs should have no border radius, on account of the fullscreen thing. In this example of a mobile calendar, the top corner has no radius, and the footer in the bottom corner does.
<img width="234" alt="Screen Shot 2022-07-11 at 1 25 20 PM" src="https://user-images.githubusercontent.com/2471874/178342575-54e9cba2-b15d-4eda-8e02-985e78dde589.png">

- [ ] Horizon select menu items missing the correct border radius when focused
<img width="199" alt="Screen Shot 2022-07-11 at 1 28 56 PM" src="https://user-images.githubusercontent.com/2471874/178343121-0900e7e5-5043-4ab3-b7c5-360fef030921.png">

- [ ] Combobox horizon - hovering items in the popover, the background color does not extend to the edge of the popover. Hard to see but notice the additional white in the corners
<img width="668" alt="Screen Shot 2022-07-11 at 1 34 17 PM" src="https://user-images.githubusercontent.com/2471874/178344098-52a3348f-4786-4377-b2c3-622da48057ab.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 19:44
- [ ] Shellbar - the SAP logo gets an outline. Since it's an action item (could be a link or a nav item) it should probably get an outline but it should be styled per Fiori look
<img width="1223" alt="Screen Shot 2022-07-11 at 3 42 56 PM" src="https://user-images.githubusercontent.com/39598672/178345615-607518a0-7fb0-46be-8c39-8ccf49f5c94d.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 19:49
- [ ] Overflow layout
some visual issues:
<img width="1199" alt="Screen Shot 2022-07-11 at 3 48 47 PM" src="https://user-images.githubusercontent.com/39598672/178346321-424b58c3-5075-4002-b3d2-aa6b26a27627.png">
<img width="1164" alt="Screen Shot 2022-07-11 at 3 48 42 PM" src="https://user-images.githubusercontent.com/39598672/178346324-8e8748b1-7b4c-4dee-9966-2d8be25ad125.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 20:02
- [ ] Overflow layout
An item from the overflow menu should go outside of the menu if selected. 
Here's the UI5 behaviour:
1. 12 items visible, the rest in overflow menu
<img width="981" alt="Screen Shot 2022-07-11 at 3 59 15 PM" src="https://user-images.githubusercontent.com/39598672/178348252-80b72f57-52b9-47cd-ac6c-42aca1ccad96.png">

2. Select Tab 26
<img width="978" alt="Screen Shot 2022-07-11 at 3 59 23 PM" src="https://user-images.githubusercontent.com/39598672/178348309-85389a39-c103-45c8-b0fa-4cbef6b9fd1d.png">

3. Tab 26 is not the last of the "visible" items
<img width="981" alt="Screen Shot 2022-07-11 at 3 59 29 PM" src="https://user-images.githubusercontent.com/39598672/178348418-345cd249-2eea-4fa2-9643-0aafce7e792f.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 20:05
- [ ] Overflow Layout Complex example
If we use the example of Avatar Group the overflow button should be following the same pattern
<img width="1221" alt="Screen Shot 2022-07-11 at 4 05 24 PM" src="https://user-images.githubusercontent.com/39598672/178348824-4438330d-ab1f-4b32-8168-d18e8d24df59.png">

**Comment by mikerodonnell89** [comment] 2022-07-11 20:12
- [ ] Datetime picker null validity example not working 
<img width="738" alt="Screen Shot 2022-07-11 at 2 07 21 PM" src="https://user-images.githubusercontent.com/2471874/178349444-07ce4fb5-a5d6-4f22-9e2f-51b11f46a32f.png">

- [ ] Fiori - Feed input right button is not vertically aligned, and this seems unique to ngx
<img width="1230" alt="Screen Shot 2022-07-11 at 2 11 50 PM" src="https://user-images.githubusercontent.com/2471874/178349890-e7bd5fa7-e1e4-412b-b89e-806f581404c1.png">

**Comment by InnaAtanasova** [comment] 2022-07-11 20:35
- [ ] Customizable Wizard
shows part of Mobile Wizard example
<img width="1671" alt="Screen Shot 2022-07-11 at 4 33 58 PM" src="https://user-images.githubusercontent.com/39598672/178353329-3f034e17-80b2-4daa-adf5-2362723b6c1f.png">

**Comment by mikerodonnell89** [comment] 2022-07-11 20:59
- [ ] List headers should not receive focus 
Screen Shot 2022-07-11 at 2.58.15 PM
From the fiori design guidelines:
<img width="591" alt="Screen Shot 2022-07-11 at 2 58 09 PM" src="https://user-images.githubusercontent.com/2471874/178357083-5743a370-2018-4c30-a359-e28b701b495d.png">

**Comment by mikerodonnell89** [comment] 2022-07-11 21:22
- [ ] RTL menu with icons issue
<img width="175" alt="Screen Shot 2022-07-11 at 3 10 48 PM" src="https://user-images.githubusercontent.com/2471874/178359123-3b432239-8ab0-45f3-bd79-8ae2b350d693.png">

- [ ] Object status - the icons on the left have some padding and the text does not, so when they have the `inverted` modifier, the text contents of the status look asymmetrical. Particularly visible for the large designs. Though there is no example on fundamental-styles docs [I think it should really be fixed in styles here](https://github.com/SAP/fundamental-styles/issues/3724)
<img width="224" alt="Screen Shot 2022-07-11 at 3 18 47 PM" src="https://user-images.githubusercontent.com/2471874/178360531-a27d999a-0d1b-4439-8ad1-59ade6c6368a.png">
<img width="191" alt="Screen Shot 2022-07-11 at 3 17 09 PM" src="https://user-images.githubusercontent.com/2471874/178360536-ec310022-74bf-4251-bfd4-1744a1ab05e2.png">

**Comment by mikerodonnell89** [comment] 2022-07-11 22:44
- [ ] I think popover controls should always receive tab focus
- [ ] If you use tab+space to open popovers, old ones don't close (by default they close when a new one is opened via mouseclick)
<img width="1538" alt="Screen Shot 2022-07-11 at 4 31 20 PM" src="https://user-images.githubusercontent.com/2471874/178369670-135f6cfa-2cc1-4655-9172-908ba16cd85c.png">

- [ ] Horizon, an active segmented button has no visual changes when it receives keyboard focus - is this by design? Noticed the same for pagination active page

**Comment by platon-rov** [comment] 2022-07-12 11:29
* calendar/date picker, safari, months & years items have wrong focus outline

<img width="367" alt="image" src="https://user-images.githubusercontent.com/20265336/178479941-e82a310a-7620-471f-b083-a82ec4b0bf10.png">

**Comment by platon-rov** [comment] 2022-07-12 11:31
* date time picker, safari, usually form message doesn't have margin

<img width="276" alt="image" src="https://user-images.githubusercontent.com/20265336/178480424-1a79fa04-cb6b-4c96-8320-6e9564a10236.png">

**Comment by platon-rov** [comment] 2022-07-12 11:33
* [ ] dialog, safari, content got selected when resizing a dialog

<img width="541" alt="image" src="https://user-images.githubusercontent.com/20265336/178480695-f2bff0b6-c42b-442d-80d0-4b8d5f2b6b74.png">

**Comment by platon-rov** [comment] 2022-07-12 11:38
* [ ] info label, safari, icon is not vertically centered

<img width="230" alt="image" src="https://user-images.githubusercontent.com/20265336/178481515-929c8f92-855a-4c24-a601-aa140daef40a.png">

**Comment by platon-rov** [comment] 2022-07-12 11:53
* [ ] segmented button, safari, currently selected button doesn't have focus outline. button either should not be focusable or have visible focus outline.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/20265336/178483883-fc2d90cf-c35e-4ad4-bb86-12acadbba540.png">

**Comment by platon-rov** [comment] 2022-07-12 11:58
* [ ] slider/docs, safari, slider handler has so high z-index so it looks weirdo if we open sidebar

<img width="525" alt="image" src="https://user-images.githubusercontent.com/20265336/178484793-24512994-6820-4c96-92e0-0da2f5a46f23.png">

**Comment by platon-rov** [comment] 2022-07-12 12:01
* [ ] split button/docs, safari, dropdown doesn't get closed after click on the button that opens sidebar

<img width="304" alt="image" src="https://user-images.githubusercontent.com/20265336/178485205-62c358ab-6220-4832-be82-cd6587be97ec.png">

**Comment by platon-rov** [comment] 2022-07-12 12:19
* [ ] table, safari, when keeping mouse button pressed on the selectable table row and moves it then row toggles its background - look weirdo

Screen Recording 2022-07-12 at 14.16.05

**Comment by g-cheishvili** [comment] 2022-07-12 12:57
> * [ ]  Content density
>   When content density is changed to `condensed` the changes are applied to all elements (in this case it's Bar component). Condensed is only applied to Table.
> 
> <img alt="Screen Shot 2022-07-11 at 2 47 26 PM" width="1627" src="https://user-images.githubusercontent.com/39598672/178336358-37281778-8bb0-4553-b98b-a1a305339ce1.png">

It is not condensed you are observing in case of bar, as stated in docs, if component does not support `condensed`, it will fall back to using `compact`

**Comment by g-cheishvili** [comment] 2022-07-12 13:04
For some reason, stackblitz examples are not working.

![image](https://user-images.githubusercontent.com/28543391/178496564-634237de-217f-4100-9ed3-6871d5eb212f.png)

**Comment by mikerodonnell89** [comment] 2022-07-12 21:06
> * [ ]  Carousel keyboard navigation
>   To reproduce:
> * go to the first example
> * focus the carousel element
> * use the Tab key to focus the arrow button
> * use the right arrow to reach the last image of the carousel
> * now that you are at the last element the focus is lost so going to the other direction using only the keyboard is not possible

They can shift+tab back to the other button, which I don't think is too confusing. I thought about setting the focus back to the carousel as a whole but that would turn in to a semi-focus trap scenario looping through the carousel and then the first carousel button again, so I think current implementation is fine. But maybe we need to ask i18n

**Comment by platon-rov** [comment] 2022-07-13 09:59
* [ ] select, safari, after option get selected and dropdown closed focus not being moved back to the select, but gets out of the page 

https://user-images.githubusercontent.com/20265336/178706940-fce6e052-d30a-4adb-a995-5d6daa411498.mov

**Comment by platon-rov** [comment] 2022-07-13 10:06
* [ ] vertical navigation, safari, no keyboard's arrow buttons support. up/down should move focus between items on the same level, left - open nested level, right - close nested level, reference https://www.w3.org/WAI/ARIA/apg/example-index/menubar/menubar-navigation

<img width="308" alt="image" src="https://user-images.githubusercontent.com/20265336/178708400-a97bafee-4fa4-48d9-9a7f-bbbb7cc40db8.png">

**Comment by platon-rov** [comment] 2022-07-13 10:17
* [ ] wizard, safari, 

* focus lost (get out of the page) after navigating to certain step
* if we are on step 2 - we can focus step 1 and go to it, but we cannot focus step 2 when we're on the step 1


https://user-images.githubusercontent.com/20265336/178710651-2d939e45-eba0-4559-8545-4187d9ffaddd.mov

**Comment by mikerodonnell89** [comment] 2022-07-13 21:55
@InnaAtanasova I think the wizard popover/mobile progress bar issues were introduced here, I guess a specific request from DXP to hide popovers under the wizard progress bar

**Comment by droshev** [comment] 2022-07-15 02:03
- [ ] compact Datepicker is not rendered properly
<img width="261" alt="Screen Shot 2022-07-14 at 10 03 11 PM" src="https://user-images.githubusercontent.com/4380815/179132040-2301139c-313c-4245-9eb9-174cc91b39b9.png">

**Comment by droshev** [comment] 2022-07-18 18:42
> 

when there is no condensed the app should go to compact instead

**Comment by droshev** [comment] 2022-07-18 20:00
> https://experience.sap.com/fiori-design-web/tree-table/

@InnaAtanasova has a point, but I think the way it is documented in the guidelines makes it very confusing. I think it would be easier to document as another option for content density (cozy > compact... >condensed) where condensed will default to compact mode except for table. @InnaAtanasova  @mikerodonnell89 what do you think?

**Comment by droshev** [comment] 2022-07-21 02:47
> > > https://experience.sap.com/fiori-design-web/tree-table/
> > 
> > 
> > @InnaAtanasova has a point, but I think the way it is documented in the guidelines makes it very confusing. I think it would be easier to document as another option for content density (cozy > compact... >condensed) where condensed will default to compact mode except for table. @InnaAtanasova @mikerodonnell89 what do you think?
> 
> The explanation of condensed mode in that link makes me think it should operate totally separately from cozy/compact. "Condensed" shouldn't be a selectable option for content density, it's just a modifier class for trees/tables

I doubt anyone can understand that feature in that way. Can we keep it simple?

**Closed** 2022-07-21 19:35 UTC
Labels: Defect Hunting
