### ISSUE TITLE
Busy State revisit

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#2000] opened 2020-02-18 19:16 UTC
#### Is this a bug, enhancement, or feature request?
We need to revisit the Busy State 
[Busy State](https://experience.sap.com/fiori-design-web/busy-state/)

**Comment by salarenko** [comment] 2020-04-29 10:31
Duplicate of #1873

**Closed by salarenko** 2020-04-29 10:31 UTC
Labels: next-grooming
