### ISSUE TITLE
Select Issue - Max Width

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#2922] opened 2020-07-28 16:01 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
Width of the Option List
By default, the width of the option list adapts to the width of the longest entry. The maximum width of the option list is set to 600 px.

https://ux.wdf.sap.corp/fiori-design-web/select/

**Comment by salarenko** [comment] 2020-09-01 09:45
Duplicate of #3015

**Closed by salarenko** 2020-09-01 09:45 UTC
Labels: bug, core
