### ISSUE TITLE
Platform: Combobox used outside of the repo

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#4251] opened 2021-01-05 12:44 UTC
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.

1. Its hard to setup Combobox in external application with just following our API DOC. We have to add quite all of setups and services which is not mentioned in the docs or its not obvious
 * Please update docs so developer can setup it without fails and tries
 
2. Combobox is missing styles
  * it needs overlay styles in docs we have to add this individually to each demo
      @import "~@angular/cdk/overlay-prebuilt.css";
   
   * Still some styles are missing.  See the example
   
   https://github.com/fkolar/fiori-combo-test

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
```
Angular CLI: 10.2.1
Node: 12.0.0
OS: darwin x64
Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.1
@angular-devkit/schematics      10.2.1
@angular/cli                    10.2.1
@schematics/angular             10.2.1
@schematics/update              0.1002.1
rxjs                            6.6.3
typescript                      3.9.7
```
#### If this is a bug, please provide steps for reproducing it.
   https://github.com/fkolar/fiori-combo-test

**Comment by Betrozov** [comment] 2021-01-05 13:07
@fkolar as I see overlay styles is present here

**Comment by fkolar** [comment] 2021-01-05 13:23
This is probably the point. And see when you use component like this outside of our docs, how one needs know what all has to be setup in order to make it this work ?

We have self-contained styles arent we ? I should not import any additional styles to make it work.

**Comment by Betrozov** [comment] 2021-01-05 18:59
Hi @fkolar 
could you please share your knowledge of what's missing in the documentation?

**Comment by droshev** [comment] 2021-06-12 11:37
@fkolar closing this as it is old. feel free to reopen if the issue is still valid

**Closed by droshev** 2021-06-12 11:37 UTC
Labels: bug, platform
