### ISSUE TITLE
[Accessibility][Sourcing] fdp-menu-item text announced twice

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#8253] opened 2022-06-20 07:53 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
when focus is on fdp-menu-item with some aria-label , the screenreader reads menu item text twice

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13 
  "@fundamental-ngx/core": "0.34.3-rc.47",
    "@fundamental-ngx/platform": "0.34.3-rc.47",

#### If this is a bug, please provide steps for reproducing it.
Open a fdp-menu using keyboard
the first item receives focus 
keep moving using down arrow and observe the screenreader reading

#### Please provide relevant source code if applicable.
This is replicable even on https://sap.github.io/fundamental-ngx/#/platform/menu 

#### Is there anything else we should know?
<img width="1792" alt="Screenshot 2022-06-20 at 1 19 25 PM" src="https://user-images.githubusercontent.com/88182358/174552405-822897c8-4d0c-4f3c-8c8c-47d56abebd7a.png">

**Comment by I543348** [comment] 2022-12-15 10:06
Not able to replicate this issue in v0.38.0-rc.2

**Comment by skaquib123** [comment] 2022-12-16 05:57
Hi @I543348, as discussed the issue is resolved and it is working as expected. I am closing the issue.

**Closed by skaquib123** 2022-12-16 05:57 UTC
Labels: platform, sourcing, menu
