### ISSUE TITLE
object status (core/platform): information icon is the wrong color

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4493] opened 2021-01-27 13:24 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
the informative icon is the wrong shade of blue

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/core/object-status
2. scroll down to the "Object Status with Text and Icon" example
3. check the informative icon color

![2021-01-27_2](https://user-images.githubusercontent.com/47522152/105996833-8a432200-60b3-11eb-8dd7-6335680717cb.png)

**Comment by sKudum** [comment] 2021-05-26 03:16
Duplicate of #3930 .Hence closing it

**Closed by sKudum** 2021-05-26 03:16 UTC
Labels: Low, bug, core
