### ISSUE TITLE
[Accessibility] Default tabIndex=0 on scrollbar inside fd-tab-list creating additional tab keypress while navigating inside tab content

### ISSUE THREAD

**Issue by harshitha-s-kanchan** [SAP/fundamental-ngx#10964] opened 2023-11-15 19:52 UTC
#### Is this a bug, enhancement, or feature request?
Bug in version 0.43.11

#### Describe your proposal.
Default tabIndex=0 on scrollbar inside `fd-tab-list` (v0.43.11) creating additional tab keypress while navigating from tab header to tab content

This seems to be fixed in ngx `0.46.1` and above. The fix needs to be downported to `0.43.11`

#### Can you handle that on the application side
No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
Angular 15
Ngx 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
When focus is on tab header/title, press tab key. 
Scroll bar with tabIndex=0 is focused (not visible on the screen), creating loss of focus in navigation.
Press tab key again, focus moves to tab content.

Issue is seen in - v0.43.11 - https://stackblitz.com/edit/bk9mou?file=package.json
Seems to be fixed in v0.46.1 - https://stackblitz.com/edit/hdddm8?file=package.json

#### Please provide relevant source code (if applicable).
https://github.com/SAP/fundamental-ngx/blob/3672ff066b2d4bf1d4dbeeb90b8fec26710c154c/libs/core/src/lib/tabs/tab-list.component.html#L102-L113

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/bk9mou?file=package.json

<img width="1715" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/149040487/09351bd2-d345-49af-94e1-8b2fa99f1c07">

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
Yes, There should be a single tab click while navigating from tab header to tab content

**Comment by droshev** [comment] 2023-11-15 22:06
@harshitha-s-kanchan the tabs are deprecated and it is advised to use the Icon Tab Bar instead.

**Comment by harshitha-s-kanchan** [comment] 2023-11-15 23:11
@droshev For our use case we need to add tab content for each tab as shown in example below for https://sap.github.io/fundamental-ngx/#/core/tabs 
```
<fd-tab-list>
    <fd-tab title="Link 1"> Content for tab 1 </fd-tab>
    <fd-tab title="Link 2"> Content for tab 2 </fd-tab>
    <fd-tab title="Link 3"> Content for tab 3 </fd-tab>
</fd-tab-list>
```

Could you please provide a similar example to add tab content for [@fundamental-ngx/platform/icon-tab-bar](https://sap.github.io/fundamental-ngx/#/platform/icon-tab-bar), so that we can check the feasibility in our use case.

**Comment by droshev** [comment] 2024-03-02 15:34
@harshitha-s-kanchan You can use the data driven Icon Tab Bar for that.

**Comment by droshev** [comment] 2024-05-22 19:51
@harshitha-s-kanchan closing the ticket since there was not any update. Please, report a new ticket if you are able to reproduce the issue using icon tab bar

**Closed by droshev** 2024-05-22 19:51 UTC
