### ISSUE TITLE
[P2][Sourcing][PLATFORM Multi-Combo box] Japanese Language - Hiragana Text invalid entry when given space in Combo box search

### ISSUE THREAD

**Issue by sathian-icd** [SAP/fundamental-ngx#12765] opened 2024-11-25 08:17 UTC
#### Is this a bug, enhancement, or feature request?

Bug

#### Describe your proposal.

 Invalid entry can be shown when the word is not present. the typed word not to be removed

#### Can you handle that on the application side

No

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)

Angular: 15
core/ platform: 0.43.47

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

Try typing in Hiragana character in multi-combo box search and give space.
Observe the typed word is removed and invalid entry is shown.

Multi-Combo box

#### Please provide stackblitz example(s).

https://stackblitz.com/edit/angular-knha3l-rlyy1o?file=src%2Fapp%2Fplatform-table-default-example.component.ts

#### Did you check the documentation and the API?

yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by mikerodonnell89** [comment] 2024-11-25 16:40
This isn't unique to Japanese, try typing "x" in this example and you'll see the same behavior, as none of the results contain the letter "x". You'll also see this on the SAP ui5 multicombobox https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox

Closing as this is the intended behavior

**Closed by mikerodonnell89** 2024-11-25 16:40 UTC
