### ISSUE TITLE
[Sourcing][Aug21] `fd-switch` does not update on toggle in `virtualScroll`

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10247] opened 2023-07-28 23:04 UTC
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

In platform table, if we have `fd-switch` and `virtualScroll` on and after we scroll pass `renderAhead`, toggle on switch does not update the label until we scroll or toggle on another switch. This happens when each `fd-switch` component is separated by at least one cell.

https://github.com/SAP/fundamental-ngx/assets/22842279/4416323d-a67a-4a1c-b859-2f773796f468

It works fine if `virtualScroll` is disabled.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

current

#### If this is a bug, please provide steps for reproducing it.

Please refer to the link below:

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-ttxut2-iyymbf?file=src%2Fapp%2Fdisplay-text.component.ts,package.json,src%2Fapp%2Fplatform-table-page-scrolling-example.component.html,src%2Fapp%2Fplatform-table-page-scrolling-example.component.ts,src%2Fapp%2Fdisplay-text-label.component.html

**Comment by fkolar** [comment] 2023-08-09 10:24
Is this a duplicate of #10171

**Comment by droshev** [comment] 2023-08-10 12:02
@N1XUS we would need to downport this to `ng15`. We can discuss internally how to tackle this.

**Closed** 2023-08-16 13:51 UTC
Labels: ng15

**Comment by CSENoni** [comment] 2023-08-17 22:43
It is working now with `0.43.5`. Thanks!
