### ISSUE TITLE
Popover is display under other components 

### ISSUE THREAD

**Issue by eliavmaman** [SAP/fundamental-ngx#2634] opened 2020-06-08 08:32 UTC
BUG

Popover is display under other components .
Attached image => popover under fd-panel-body

![image](https://user-images.githubusercontent.com/6911449/84009182-93904a80-a97b-11ea-883f-076ecc2cab7f.png)

**Comment by JKMarkowski** [comment] 2020-06-08 12:25
Hello @eliavmaman,
Could you create some stackblitz example, where this problem occurs? I'm not able to reproduce it

**Comment by droshev** [comment] 2020-12-10 01:28
@eliavmaman i am closing the issue as it is getting old. In case you have issues, feel free to open a new one or re-open this one.

**Closed by droshev** 2020-12-10 01:28 UTC
