### ISSUE TITLE
BUG. Core. Select components. Disabled select is skipped by the tab action. 

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4819] opened 2021-03-02 12:41 UTC
#### Is this a bug, enhancement, or feature request?
BUG
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.28.1-rc.13
#### If this is a bug, please provide steps for reproducing it.
SR: 
1. Open Select component page (Core)
2. Navigate to the first example.
3. Put the focus on Compact select example. 
4. Click Tab. 
AR: Select in read-only mode example is in focus. 
ER: Select in disabled mode example is in focus. 

https://user-images.githubusercontent.com/5969492/109649892-2a81e000-7b65-11eb-9db3-323c8ce60eb4.mov

**Comment by sKudum** [comment] 2021-03-03 17:00
Could you please point us to Fiori guidelines on it.what is expected behaviour in this case.

**Comment by sKudum** [comment] 2021-05-25 12:27
Issue is logged in https://github.com/SAP/fundamental-ngx/issues/5051 as well. Closing this considering it as duplicate of the same.

**Closed by sKudum** 2021-05-25 12:27 UTC
Labels: accessibility, bug, core
