### ISSUE TITLE
Accessibility Testing_Platform_Object Status

### ISSUE THREAD

**Issue by fanjum-acc** [SAP/fundamental-ngx#5768] opened 2021-06-24 11:40 UTC
Hello Colleagues,

Please find attached error document for control: Platform_Object Status

[Object Status_Platform_Ariba Controls.docx](https://github.com/SAP/fundamental-ngx/files/6708841/Object.Status_Platform_Ariba.Controls.docx)

**Comment by manu-kr** [comment] 2021-08-25 09:03
@Sanjay-1312 Related to issue 6 and 7
![image](https://user-images.githubusercontent.com/53512176/130759856-1bc8bc72-9c2e-4813-8787-938a008f85c8.png)
 is acceptable as per the Fiori3 visual spec PFB attached screentshot. So I am closing this as not a bug.
<img width="910" alt="Screenshot 2021-08-25 at 2 32 00 PM" src="https://user-images.githubusercontent.com/53512176/130761719-c4759582-f626-4815-9917-5442a11c99b5.png">

**Closed** 2021-09-06 14:15 UTC
Labels: bug, platform, ATL
