### ISSUE TITLE
Clearing datepicker input then typing a number will automatically select a new date and fill the input

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-ngx#838] opened 2019-05-22 21:16 UTC
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

Should behave the same as datetime picker

**Comment by MattL75** [comment] 2019-05-24 13:22
Not sure there's a clean solution to this. This is a cascading problem from using the JS Date object - which is why I built own own for calendar2 which is a bit on hold right now while I deal with other issues

**Comment by mikerodonnell89** [comment] 2019-05-24 20:23
True.  This only "works" for the datetime picker because the input validation for that component is looking for "am" or "pm" at the end of the string.  Let's revisit this after the calendar refactor

**Comment by droshev** [comment] 2019-06-26 13:28
duplicate of #967 
@mikerodonnell89 can you retest once we merge all open PRs related to datepicker?

**Closed** 2019-06-28 15:44 UTC
Labels: bug, datepicker
