### ISSUE TITLE
Bug: Platform Table Phase 3 enchancements defect hunting issues 

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#4735] opened 2021-02-22 06:52 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.

1).With Keyboard  not able to access/perform operations.
2). On tab can't focus on expand/collapse arrows.

<img width="655" alt="2021-02-22_12-34-44" src="https://user-images.githubusercontent.com/53487468/108673849-66d09300-750a-11eb-89d1-8489a860a9c5.png">

3).On page load console shows errors and unwanted logs.

<img width="1680" alt="2021-02-22_12-07-08" src="https://user-images.githubusercontent.com/53487468/108671948-45ba7300-7507-11eb-8d50-be5e547be3b5.png">

5).Can't  scroll in "page scroll" example on keypress.
6).Examples are not in support to test for screen readers.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
 v 0.28.0-rc.2 

#### If this is a bug, please provide steps for reproducing it.
bug

**Comment by olshansky** [comment] 2021-02-22 15:04
@sKudum 
1)&nbsp;Which operations? 
2)&nbsp;The row with arrow accessible by keyboard and could expand/collapse grouped rows, I believe it's enough 
3)&nbsp;Can't reproduce error [here](https://fundamental-ngx.netlify.app/#/platform/table) _(maybe it was fixed)_. As for logs after error – it's feature examples, e.g. when you mark the checkbox of the row as checked it will fire an event.

5)&nbsp;investigating it
6)&nbsp;investigating it

**Comment by sKudum** [comment] 2021-02-22 16:21
> @sKudum
> 1) Which operations?

    Hi @olshansky ,
    checkbox, radiobuttons, filters etc are not selectable via keyboard.


> 2) The row with arrow accessible by keyboard and could expand/collapse grouped rows, I believe it's enough
> 3) Can't reproduce error [here](https://fundamental-ngx.netlify.app/#/platform/table) _(maybe it was fixed)_. As for logs after error – it's feature examples, e.g. when you mark the checkbox of the row as checked it will fire an event.
> 
> 5) investigating it
> 6) investigating it

**Comment by platon-rov** [comment] 2021-04-08 13:13
@olshansky I guess that issue should be closed as related PR is merged, isn't it?

**Comment by olshansky** [comment] 2021-04-09 12:19
> @olshansky I guess that issue should be closed as related PR is merged, isn't it?
> 
> But I see you left `TODO:` in code with the PR ([reference](https://github.com/SAP/fundamental-ngx/blob/main/libs/platform/src/lib/components/table/table.component.ts#L590)) do an issue raised about that todo?

I'm not 100% sure that the issue could be closed (cc: @sKudum).

As for keyboard navigation, it has no separate issue, it was planned as a part of one of the phases.

**Comment by platon-rov** [comment] 2021-04-09 14:18
May be relative: #5094.

**Comment by olshansky** [comment] 2021-04-22 06:50
The rest issues could be resolved with keyboard navigation support (#5094)

**Closed by olshansky** 2021-04-22 06:50 UTC
Labels: Defect Hunting, High, bug
