### ISSUE TITLE
Accessibility Bug: The focus to background for the button in the shell bar is not satisfying the minimum color contrast ratio of 4.5:1

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3150] opened 2020-08-30 05:09 UTC
Fundamental core component: "Product Switch"

Description: The focus to background for the button in the shell bar is not satisfying the minimum color contrast ratio of 4.5:1

Expected: The focus to background for all the buttons should satisfy the minimum color contrast ratio of 4.5:1.

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651662-14f40680-eaad-11ea-9b0d-cfeb2dbd692c.png)

**Comment by kavya-b** [comment] 2021-04-30 09:27
@puru-hk @manjunathanagaraj 
The values are as specified in the spec:
![image](https://user-images.githubusercontent.com/53509521/116675739-c7c18f00-a9c3-11eb-8f8b-7b979de7e32c.png)
![image](https://user-images.githubusercontent.com/53509521/116676020-1ec76400-a9c4-11eb-8318-50898024c0cb.png)
spec:
![image](https://user-images.githubusercontent.com/53509521/116675958-0bb49400-a9c4-11eb-9769-3fc2e9831d48.png)

This is implemented as per spec; this issue can be sent out to designers to provide different colors that comply to the contrast ratio.

**Comment by kavya-b** [comment] 2021-05-04 09:08
@Seamoo13 @puru-hk please verify from your end as well

**Comment by puru-hk** [comment] 2021-05-26 07:02
I have tested this issue it is working as expected. see the attachment 
<img width="511" alt="Screenshot 2021-05-26 at 12 30 44" src="https://user-images.githubusercontent.com/32538291/119616540-5805bf00-be1e-11eb-8231-94a0fd3b13e7.png">

@Sanjay-1312 Please retest and close this issue

**Comment by Sanjay-1312** [comment] 2021-05-27 02:59
Hello Colleagues,

The color contrast for the 'Product Switch' is meeting minimum contrast ratio.
The issue is fixed. Hence Closing the ticket.

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-05-27 02:59 UTC
Labels: ATL, Low, QA Approved, bug, core
