### ISSUE TITLE
bug(platform): list datasource gets data only once

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-ngx#8961] opened 2022-11-15 12:22 UTC
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
Currently, list's datasource gets data only once and all future updates are being ignored.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
current

**Comment by DimitarVoynov** [comment] 2022-11-15 14:17
hi @N1XUS, thanks for reporting/following up on this. 
We just noticed something else which root cause seems the same as you described it above. With the latest fdp version (0.36.2) when we use `dataSource` with Observable<(custom_type>[] like this:

`[dataSource]="displayRows | async"`

where

` displayRows: Observable<Notification[]>;`

NO data at all is displayed in the list.

Do you think the root cause is the same?

**Comment by N1XUS** [comment] 2022-11-18 08:45
@DimitarVoynov Hello. Might be. Meanwhile, could you maybe try something for me: when data in displayRows, can you call ChangeDetectorRef's detectChanges for the component which uses list component?

**Comment by g-cheishvili** [comment] 2022-11-29 22:00
https://angular-qeewgl.stackblitz.io
Hi @DimitarVoynov, can you please check if this example has a solution for your issue?

**Comment by ivzhelev** [comment] 2022-11-30 23:04
Thanks @g-cheishvili , but the link is not accessible and leads to:
**Error fetching cached project bundle for preview.**
Could you please double-check the link is correct, 10x in advance.

**Comment by g-cheishvili** [comment] 2022-11-30 23:18
https://stackblitz.com/edit/angular-qeewgl?file=src/app/platform-list-border-less-example.component.ts

@ivzhelev Check this

**Comment by ivzhelev** [comment] 2022-12-01 23:25
This one opens correctly, let me check the example and will provide update here, thanks.

**Comment by ivzhelev** [comment] 2022-12-02 10:30
@g-cheishvili thanks for the link. It seems this is a solution for the issue. 
Just one question- the example in the link is:
```
<fdp-list [noBorder]="true" [dataSource]="_dataSource" id="cozy-list">
  <fdp-standard-list-item
    *fdpItemDef="let address"
    [title]="address.name"
    [ariaLabel]="address.name"
  >
  </fdp-standard-list-item>
</fdp-list>
```
where 
```
_dataSource = new ListDataSource<Address>(this._listDataProvider);
```

while in our case it is like that:

```
<fdp-list [noBorder]="true" [dataSource]="_dataSource | async" id="cozy-list">
  <fdp-standard-list-item
    *fdpItemDef="let address"
    [title]="address.name"
    [ariaLabel]="address.name"
  >
  </fdp-standard-list-item>
</fdp-list>
```
where 
```
_dataSource : Observable<Notification[]>;
```

so would the proposed solution work also in the case where the **_datasource** is **Observable** and we access it in the html file with ** [dataSource]="_dataSource | async"**?
If it would work, then this would be great. 
Thanks in advance.

**Comment by ivzhelev** [comment] 2022-12-02 10:30
@g-cheishvili thanks for the link. It seems this is a solution for the issue. 
Just one question- the example in the link is:
```
<fdp-list [noBorder]="true" [dataSource]="_dataSource" id="cozy-list">
  <fdp-standard-list-item
    *fdpItemDef="let address"
    [title]="address.name"
    [ariaLabel]="address.name"
  >
  </fdp-standard-list-item>
</fdp-list>
```
where 
```
_dataSource = new ListDataSource<Address>(this._listDataProvider);
```

while in our case it is like that:

```
<fdp-list [noBorder]="true" [dataSource]="_dataSource | async" id="cozy-list">
  <fdp-standard-list-item
    *fdpItemDef="let address"
    [title]="address.name"
    [ariaLabel]="address.name"
  >
  </fdp-standard-list-item>
</fdp-list>
```
where 
```
_dataSource = new ListDataSource<Address>(this._listDataProvider);
_dataSource : Observable<Notification[]>;
```

**Comment by g-cheishvili** [comment] 2022-12-02 11:02
Yes, that should work, only one caveat, before [this](https://github.com/SAP/fundamental-ngx/issues/8996) is closed, you'll have a limit of 5 items visible when you pass items. Also, you can directly pass `Observable<T[]>`, with no need for `async` and it will work. The difference is that when a new value is passed, a list creates datasource from scratch, whereas, if it is `Observable` of the list, it updates the list items in a similar fashion that I posted.
Also bear in mind that every new Value passed to the list, should be different. They should have different reference. If you mutate array, it will not update visually. This is because mutated array is always same as before, only contents are changed. Basically think about it like this: `ArrayBefore === ArrayNow`, if this expression is false, no updates will be made to the UI.

**Comment by ivzhelev** [comment] 2022-12-02 13:15
perfect, thanks @g-cheishvili for the details.

**Comment by g-cheishvili** [comment] 2022-12-02 22:16
> perfect

Cool, I will close this then.

>  thanks @g-cheishvili for the detailed explanation.

My pleasure, glad if I helped

**Closed by g-cheishvili** 2022-12-02 22:16 UTC
Labels: dxp, 0.37
