### ISSUE TITLE
wizard flickers when moving to summary page

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5797] opened 2021-06-25 00:58 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
- [ ] Quick flicker when moving to the summary page on the wizard

**Comment by mikerodonnell89** [comment] 2021-07-07 17:12
> * [ ]  RTL mode have some issues with navigation items placement:
>   ![image](https://user-images.githubusercontent.com/6586561/118948348-dc5ccb80-b960-11eb-974d-fdcd52d906da.png)

Issue originates in fundamental-styles:
<img width="404" alt="Screen Shot 2021-07-07 at 1 11 08 PM" src="https://user-images.githubusercontent.com/2471874/124801409-d036c880-df24-11eb-9588-a4f3bda6dde8.png">

**Comment by mikerodonnell89** [comment] 2022-07-28 19:35
Upon recording a video and going frame by frame it appears the flicker is caused by the progress bar disappearing after clicking submit and before moving to the summary page

**Closed** 2022-08-04 11:33 UTC
Labels: bug, core, Defect Hunting, denoland, wizard
