### ISSUE TITLE
[BUG]. Core. Select. Option list should collapse on outside click 

### ISSUE THREAD

**Issue by AntonOlkhovskyi** [SAP/fundamental-ngx#4711] opened 2021-02-18 09:01 UTC
#### Is this a bug, enhancement, or feature request?
Bug.
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
0.27.1-rc.3
#### If this is a bug, please provide steps for reproducing it.
SR: 
1. Open Core => Select => Adding and Removing Options example
2. Open the options list. 
3. Click anywhere on the page (outside options list)
ER: Options list is collapsed. 
AR: Options list is still shown
#### Is there anything else we should know?
Affected examples: Programmatic Control; Adding and Removing Options;

https://user-images.githubusercontent.com/5969492/108324010-0c64c900-71d0-11eb-9be1-3bd98929545d.mov

**Comment by sKudum** [comment] 2021-02-22 04:10
It is feature provided to not to close with the help of property closeonoutsdeclick=false. It is not a bug hence closing it.

**Closed by sKudum** 2021-02-22 04:10 UTC
Labels: E2E automation, Low, bug, core, low priority
