### ISSUE TITLE
When searching for a filter in Multi input , a non-matching text get the bold font

### ISSUE THREAD

**Issue by ambikesh-SAP** [SAP/fundamental-ngx#11781] opened 2024-04-19 06:24 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
We are using Multi-input provided by fundamental-ngx library. Whenever we use the `[includes]="true"`, the search result has non-matching text get the bold font.

This was working before as expected but it has broken somewhere in between 0.40.x & latest.

#### Can you handle that on the application side
NO

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
0.49.x

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;

https://github.com/SAP/fundamental-ngx/assets/162120960/afef5cbc-8505-4db2-9c55-d965fa862d14

#### Please provide stackblitz example(s).
Can be replicated in https://sap.github.io/fundamental-ngx/#/core/multi-input:~:text=results%20including%20search-,term,-By%20default%2C%20the ;

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?

**_IMPORTANT: Please refrain from providing links or screenshots of SAP's internal information, as this project is open-source, and its contents are accessible to anyone._**

**Comment by alexhristov14** [comment] 2024-08-14 13:25
@ambikesh-SAP I was able to reproduce the error but only in the 0.49 version of ngx. From 0.50.x on out, it seems to be fine and fixed. Please let me know if the error still occurs after updating the version so I can close this issue.

**Comment by droshev** [comment] 2024-08-14 13:32
@alexhristov14 thanks for checking it out. @ambikesh-SAP you would need to migrate to the latest

**Closed by droshev** 2024-08-14 13:32 UTC
