### ISSUE TITLE
documentation is not responsive

### ISSUE THREAD

**Issue by mscud** [SAP/fundamental-ngx#417] opened 2019-01-16 14:28 UTC
![screenshot_20190116-124242](https://user-images.githubusercontent.com/545229/51255359-594b9500-19a3-11e9-993b-07f63b726530.png)

**Comment by mikerodonnell89** [comment] 2019-01-17 22:13
possible duplicate of https://github.com/SAP/fundamental-ngx/issues/347

**Comment by MattL75** [comment] 2019-01-18 00:59
I think #347 is requesting a full collapsing feature on the sidenav component while this issue is commenting on a broken docs site for mobile

**Closed** 2019-01-18 20:12 UTC
Labels: bug, documentation
