### ISSUE TITLE
[Sourcing][Accessibility]: fdp-table platform navigation reading issues.

### ISSUE THREAD

**Issue by aamirshah01** [SAP/fundamental-ngx#9527] opened 2023-03-16 11:56 UTC
#### Is this a bug, enhancement, or feature request?
Bug.
#### Briefly describe your proposal.
In our application we have used the fdp-table with custom cells and the team have found issues as follows:

1. On accessing data within table ‘Risk projects’, their corresponding column headers are not being associated when read.
2. On accessing the list items of combo box ‘Display’, their corresponding item counts are not read to the users.
3. On accessing the elements within ‘Risk projects’ section, their corresponding header is not being associated when read.
4. On accessing the date within table ‘Risk projects’, its corresponding UI type “Table” and label is not conveyed to the users when read.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular: ^15.2.0
NGX: 0.38.2

#### If this is a bug, please provide steps for reproducing it.
See internal Channel 
#### Is there anything else we should know?
This is happening in https://fundamental-ngx.netlify.app/#/platform/table as well which is recorded as well.

The testing team have reported in windows using JAWS. ( attached the screenshot of them as well).

**Comment by aamirshah01** [comment] 2023-03-16 12:07
https://user-images.githubusercontent.com/59820279/225612196-4508148a-ab2a-40e8-a0f5-0bd95abecaf1.mp4

**Comment by aamirshah01** [comment] 2023-03-16 12:10
![Picture1](https://user-images.githubusercontent.com/59820279/225613209-7f49b0b6-d5e3-41f9-b57d-25b31708ef96.png)

**Comment by aamirshah01** [comment] 2023-03-16 12:11
![Picture1 (1)](https://user-images.githubusercontent.com/59820279/225613343-540ec11c-d998-4e3f-a1cd-be1132b6a399.png)

**Comment by aamirshah01** [comment] 2023-03-16 12:12
![Picture1 (2)](https://user-images.githubusercontent.com/59820279/225613467-c9ace5ac-ce52-471d-b830-eceedfe9fc8d.png)

**Comment by aamirshah01** [comment] 2023-03-16 12:12
![Picture1 (3)](https://user-images.githubusercontent.com/59820279/225613583-78e1399b-06cb-4e35-ac49-e8b517f91bfe.png)

**Comment by fkolar** [comment] 2023-03-30 17:33
@aamirshah01 , 

1. Please never share internal credentials and URL to SAP internal systems
2. This is going to be hard to tackle as this is only based on the videos
3. Since you are also mentioning this is also reproducible on fnd-ngx table can you maybe describe the usecase there and dont mention RiskProject?

**Comment by aamirshah01** [comment] 2023-04-03 01:52
@fkolar : Thanks for your suggestions and will keep this in mind.
What the issues raised by the team are as :
For example : On accessing data within table name say ‘Risk projects’, their corresponding column headers are not being associated when read. 
Which means the text you see here there is no mention of table name while reading headers like Column 2 of 9 it should prefix with table name as well
https://github.com/SAP/fundamental-ngx/issues/9527#issuecomment-1471840423


Same kind of behavior is expected on other issues.

Let me know if you need more info.

**Comment by fkolar** [comment] 2023-04-05 07:06
@aamirshah01 , Thank you for removing screenshot and URL from internal application, but would you be able to replicate the behavior also on the fundamentals DOCS API site? so we can test it there, or create some stackblitz sample?

**Comment by mikerodonnell89** [comment] 2023-05-16 22:54
Column headers are being read, the table title and "table" are being read, not sure what you are talking about regarding the combobox and without some example I can't really help there. Closing this issue for now but please reopen or open another with a stackblitz example if this is still an issue. Speech history screenshot below of accessing the table, focusing items etc.
![Screenshot 2023-05-16 at 4 51 35 PM](https://github.com/SAP/fundamental-ngx/assets/2471874/d29e4164-7c17-4b38-9cc4-3c0eba1285ce)

**Closed by mikerodonnell89** 2023-05-16 22:54 UTC
Labels: question

**Comment by I543348** [comment] 2023-05-18 06:21
@aamirshah01  pls evaluate the fix
