### ISSUE TITLE
bug(platform): Not possible to add sap icon in list items

### ISSUE THREAD

**Issue by burise** [SAP/fundamental-ngx#8676] opened 2022-09-12 09:04 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Using the fdp-list, it is not possible to set a glyph / sap icon instead of an avatar inside a standard list item.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular: 13.2.4
Fundamental Library: 0.33.7

#### If this is a bug, please provide steps for reproducing it.
Add an fdp-list with one or more standard-list-items to your html. Observe that you cannot set a glyph / SAP icon as an avatar for the list items. Ideally, there should be an property `glyph` that can be used inside the standard-list-item definition, similar to what fdp-button allows (https://sap.github.io/fundamental-ngx/#/platform/button#icons).

#### Please provide relevant source code if applicable.
n/a

#### Is there anything else we should know?
n/a

**Comment by mikerodonnell89** [comment] 2022-09-30 19:45
You can accomplish this in the meantime with the less opinionated core list - but this is a feature we could add to platform list in the future (maybe allowing devs to pass a template to the fdp-standard-list-item)

**Comment by mikerodonnell89** [comment] 2022-09-30 19:59
Closing as this is essentially a duplicate of #8657

**Closed by mikerodonnell89** 2022-09-30 19:59 UTC
Labels: enhancement
