### ISSUE TITLE
Accessibility Bug: There is no text alternative in the form of tooltip provided for the highlighted ‘image’ buttons.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3138] opened 2020-08-30 04:40 UTC
Fundamental core component: "Popover"

Description: There is no text alternative in the form of tooltip provided for the highlighted ‘image’ buttons.

Expected: The text alternative should be provided for every non-text content element which fulfills the purpose of the content

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651316-f55adf00-eaa8-11ea-8895-8131f9f2f99d.png)

**Comment by puru-hk** [comment] 2021-05-28 08:00
Tested in PR5481 demo url. It is working as expected.

**Comment by puru-hk** [comment] 2021-05-29 01:05
@Sanjay-1312 Please retest this issue in this url: https://deploy-preview-5481--fundamental-ngx.netlify.app

**Comment by Sanjay-1312** [comment] 2021-05-31 07:12
Hello Colleagues,

The issue is fixed.
Hence closing the ticket.

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-05-31 07:12 UTC
Labels: ATL, Medium, QA Approved, bug, core
