### ISSUE TITLE
Accessibility Bug: The label ‘50 items’ and ’70 items’ are not conveyed(Screen reader) when the page numbers are accessed

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3128] opened 2020-08-28 11:50 UTC
Fundamental core component: "Pagination"

Description: The label ‘50 items’ and ’70 items’ are not conveyed(Screen reader) when the page numbers are accessed

Expected: The ‘number of items’ label should get associated with the page numbers.

Attached screenshot:

![image](https://user-images.githubusercontent.com/32538291/91557759-b74ba700-e952-11ea-89e0-281ed3be4e90.png)

**Comment by puru-hk** [comment] 2021-06-04 12:53
@Sanjay-1312 Could you please retest this issue in this url https://deploy-preview-5460--fundamental-ngx.netlify.app

**Comment by Sanjay-1312** [comment] 2021-06-07 03:32
Hello Colleagues,

The issue is fixed.
Hence Closing the ticket.
URL: https://deploy-preview-5460--fundamental-ngx.netlify.app
JAWS 2021

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-06-07 03:32 UTC
Labels: ATL, Medium, Screen Reader, bug, core
