### ISSUE TITLE
[Sourcing] fdp-table Check box_ UI type and state is not read

### ISSUE THREAD

**Issue by snigdhaman** [SAP/fundamental-ngx#10344] opened 2023-08-15 02:52 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
For a fdp-table with multi-select attribute true, the checkbox should read the UI type & state through screen reader tool

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16

#### If this is a bug, please provide steps for reproducing it.
Access the checkbox of a multi-select fdp-table through screen reader tool.

#### Please provide relevant source code if applicable.
        <fdp-table #table 
                [dataSource]="source"
                [selectionMode]="selectionMode"
                [selectedKey]="'selected'"
                emptyTableMessage="No data found"
                [virtualScroll]="true"
                [expandOnInit]="true"
                bodyHeight="61vh"
                [noVerticalBorders]="true"
                [noOuterBorders]="true"
                [highlightNavigatedRow]="true"
                (rowSelectionChange)="onRowSelectionChange($event)">

#### Is there anything else we should know?
This is an accessibility bug which has an impact on Guided Sourcing application

![Picture1](https://github.com/SAP/fundamental-ngx/assets/12679774/bce7c5c8-8c7d-4005-988a-344e530631db)

**Comment by I543348** [comment] 2023-08-22 10:58
Duplicate of https://github.com/SAP/fundamental-ngx/issues/10278
cc: @snigdhaman

**Closed** 2023-08-27 14:01 UTC
