### ISSUE TITLE
[Sourcing][High][Jul] <fdp-table> Table configuration issue with virtualScroll

### ISSUE THREAD

**Issue by CSENoni** [SAP/fundamental-ngx#10039] opened 2023-06-17 04:28 UTC
#### Is this a bug, enhancement, or feature request?

bug

#### Briefly describe your proposal.

When we enable set [virtualScroll] = true or don't add it to platform table, it is working fine. However, when we set [virtualScroll]=false, the table does not show data.

https://github.com/SAP/fundamental-ngx/assets/22842279/210f4284-9369-4992-820f-9bd52880ae15

Also, some console errors when virtualScroll is enabled:

<img width="1104" alt="Screenshot 2023-06-16 at 9 23 20 PM" src="https://github.com/SAP/fundamental-ngx/assets/22842279/3361d0b7-95c2-4e94-ae24-557b0d4d05c4">

After update it in our app, for some components, I observe there is issue with dataSource but I could not replicate it in blitz:

<img width="541" alt="Screenshot 2023-06-16 at 9 26 36 PM" src="https://github.com/SAP/fundamental-ngx/assets/22842279/bc249cd7-8737-45d9-b387-27081acf0de3">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

0.42.0-rc.24

#### If this is a bug, please provide steps for reproducing it.

set virtualScroll = true or false or don't add it. 

#### Please provide relevant source code if applicable.

https://stackblitz.com/edit/angular-hsaghs?file=src%2Fapp%2Fplatform-table-page-scrolling-example.component.html

**Comment by fkolar** [comment] 2023-06-26 11:43
Also added myself as assignee, in case I will be able to do it earlier. In any other case please let me know what you started to work on it or not. thanks

**Comment by fkolar** [comment] 2023-06-27 09:34
Closing, I pulled latest and could not reproduce this issue anymore.

**Closed by fkolar** 2023-06-27 09:34 UTC

**Comment by CSENoni** [comment] 2023-06-27 16:32
I cannot reproduce this issue with v0.42.1-rc.4 on blitz. Thanks!
