### ISSUE TITLE
Accessibility Testing_Core_Object identifier

### ISSUE THREAD

**Issue by surbhi175** [SAP/fundamental-ngx#5803] opened 2021-06-25 05:18 UTC
Hi Team,

Please find the error document attached for Core_Object identifier.

[Object Identifier_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6715331/Object.Identifier_Core_ARIBA.Controls.docx)

Observed Behavior:

While accessing ‘Tables’ section within Object Identifier controls screen, the table available cannot be accessed using tab key. Therefore, the table is not accessible with keyboard.

Expected Behavior:

Ideally, all the UI elements should be accessible using keyboard. i.e. the table should be accessible using tab key.

![image](https://user-images.githubusercontent.com/53509521/126938773-ca68e362-4a8b-4b68-83ab-ceb34e9bc294.png)

**Comment by kavya-b** [comment] 2021-07-26 05:46
@surbhi175 @Sanjay-1312  The issue is related to underlying core Table component and not directly related to object identifier. Could you please modify this issue to reflect the Table component or create a new one for the Table component?

**Comment by kavya-b** [comment] 2021-08-03 02:23
@surbhi175 @Sanjay-1312 the underlying issue is captured as part of Table component's(core) issue [here](https://github.com/SAP/fundamental-ngx/issues/6178): 
![image](https://user-images.githubusercontent.com/53509521/127947393-de66a4d0-4088-447b-91b5-f4d2ef0fe548.png).  
This issue will be auto-fixed if 6178 is fixed and is dependent on it. Please confirm if this issue should be marked as `blocked` or should be closed as it is not really object identifier issue?
cc: @puru-hk @manjunathanagaraj

**Comment by puru-hk** [comment] 2021-08-05 07:59
@surbhi175 As per the above comment we will be addressing the same issue in 6178. This issue can be close.

**Comment by Sanjay-1312** [comment] 2021-08-17 07:14
Hello Colleagues, 

As per the above comment i am closing this incident,
Further this will be handled in above mentioned ticket number '6178'

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-08-17 07:14 UTC
Labels: bug, core, ATL
