### ISSUE TITLE
Sprint 123 Defect hunting - Horizon Testing

### ISSUE THREAD

**Issue by g-cheishvili** [SAP/fundamental-ngx#10649] opened 2023-10-02 20:49 UTC
Issues that are found during the deffect hunt

**Comment by g-cheishvili** [comment] 2023-10-03 09:14
Core grid list keyboard navigation is not bound to the grid list container. If you arrive at the last item in any of the grid list containers and click "arrow right" it will jump to the next example component. Additionally, grid list item does not have ability to have navigation vertically. Only `arrow right` and `arrow left` work

**Comment by g-cheishvili** [comment] 2023-10-03 09:14
<img width="738" alt="DH Autocomplete is enabled for combobox" src="https://github.com/SAP/fundamental-ngx/assets/28543391/43924f6a-d33a-411c-8007-0348fea32f91">
Autocomplete is still enabled in Combobox example

**Comment by g-cheishvili** [comment] 2023-10-03 09:15
<img width="1578" alt="DH breadcrumbs incorrect routes" src="https://github.com/SAP/fundamental-ngx/assets/28543391/e2ada899-4c20-4650-b31f-f3d93fa22c86">
Breadcrumbs RouterLink example has incorrect routes attached to it and as a result user will not be able to see correct navigation when clicked on a example

**Comment by g-cheishvili** [comment] 2023-10-03 09:16
Core illustrated message inline SVG example calls `inject` outside of the Injection Context

**Comment by g-cheishvili** [comment] 2023-10-03 09:17
<img width="1251" alt="Screenshot 2023-10-03 at 13 17 05" src="https://github.com/SAP/fundamental-ngx/assets/28543391/16f039e5-231d-4597-9042-0bd7ce660327">
Arrow is in a wrong place. Popover placement.

**Comment by g-cheishvili** [comment] 2023-10-03 09:21
<img width="708" alt="Screenshot 2023-10-03 at 13 20 50" src="https://github.com/SAP/fundamental-ngx/assets/28543391/cf086314-1e1d-45ad-8a24-5f8240dc633d">
Micro process flow shows incorrectly labels. They are cut out

**Comment by g-cheishvili** [comment] 2023-10-03 09:27
<img width="1260" alt="Screenshot 2023-10-03 at 13 26 06" src="https://github.com/SAP/fundamental-ngx/assets/28543391/bcadf319-23c0-4e7e-8620-70ca7383f827">

Does not look compact to me, plus example description mentions removed property `compact`

**Comment by g-cheishvili** [comment] 2023-10-03 09:28
<img width="1181" alt="Screenshot 2023-10-03 at 13 28 06" src="https://github.com/SAP/fundamental-ngx/assets/28543391/ff94d945-2e7e-4cde-9a78-dfe284f15a10">

When you start resizing popover, it starts selecting everything that is behind

**Comment by g-cheishvili** [comment] 2023-10-03 10:07
<img width="1407" alt="Screenshot 2023-10-03 at 14 07 07" src="https://github.com/SAP/fundamental-ngx/assets/28543391/305ae1fe-b006-4e63-90b1-b1b062a7b30d">

Drag and drop does not work on card layout

**Comment by g-cheishvili** [comment] 2023-10-03 10:46
<img width="1427" alt="Screenshot 2023-10-03 at 14 45 41" src="https://github.com/SAP/fundamental-ngx/assets/28543391/5599ae06-093c-4cc1-9a42-93eef22da5e6">

Platform search field's category seems out of the context

**Comment by g-cheishvili** [comment] 2023-10-03 10:47
<img width="1167" alt="Screenshot 2023-10-03 at 14 47 05" src="https://github.com/SAP/fundamental-ngx/assets/28543391/8355355a-1015-4414-8371-ddff54870e4b">

Smart filter bar docs page

**Comment by g-cheishvili** [comment] 2023-10-03 10:49
<img width="1151" alt="Screenshot 2023-10-03 at 14 48 26" src="https://github.com/SAP/fundamental-ngx/assets/28543391/e5dc2462-a39d-4076-a484-5115478d897e">

Platform upload collection

**Comment by g-cheishvili** [comment] 2023-10-03 10:52
<img width="1934" alt="Screenshot 2023-10-03 at 14 51 18" src="https://github.com/SAP/fundamental-ngx/assets/28543391/35bfaf33-0191-40de-a60e-a47a09a34935">

Platform form generator hint template should not be rendered like this

**Comment by mikerodonnell89** [comment] 2023-10-10 19:05
I thought this issue should have been fixed by https://github.com/SAP/fundamental-ngx/pull/10574 but I am still seeing it on the main branch

<img width="410" alt="Screenshot 2023-10-10 at 3 03 14 PM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/3b2c5a0c-c2d4-429a-aa64-27c3310c7379">

**Comment by mikerodonnell89** [comment] 2023-10-10 22:04
After closing/dismissing a dialog, we should be bringing the focus back to the previously focused element. Now it is going back to the start of the page

**Comment by mikerodonnell89** [comment] 2023-10-10 22:11
When a feed list item has more text than allowed by the maxChars input, there's no way to click the "____ more" text via keyboard. It can be focused but space/enter does not click the link

**Comment by mikerodonnell89** [comment] 2023-10-10 22:14
Inline help tooltips not displaying properly - looks similar to the error message styling issue i mentioned above
<img width="268" alt="Screenshot 2023-10-10 at 6 13 26 PM" src="https://github.com/SAP/fundamental-ngx/assets/2471874/c6463ba5-b614-40d6-85de-e110041cb358">

**Comment by mikerodonnell89** [comment] 2023-10-11 12:19
Popover focusAutoCapture does not focus the first tabbable element immediately after opening

**Comment by droshev** [comment] 2023-10-11 13:49
multi input(core) - adding custom tokens is kinda broken
<img width="767" alt="Screenshot 2023-10-11 at 9 48 52 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/f26904f5-5dc6-41a1-a7ab-1a177ce7026f">

**Comment by droshev** [comment] 2023-10-11 13:50
the hamburger menu isn't responding
<img width="199" alt="Screenshot 2023-10-11 at 9 49 58 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/b58511d7-6fc4-4082-83fd-0b60ca6d7b6a">

**Comment by droshev** [comment] 2023-10-11 13:55
Tile Title in NGX isn't as bold as in styles:
NGX:
<img width="199" alt="Screenshot 2023-10-11 at 9 49 58 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/38e31c15-09f0-4314-892b-453499934304">

Styles:
<img width="206" alt="Screenshot 2023-10-11 at 9 54 59 AM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/b7ebdddd-e559-40a3-b093-7f2385735b89">

**Comment by droshev** [comment] 2023-10-11 13:58
Variant management/Smart Filter Bar spacing isn't 100% matching the visual specification

**Comment by InnaAtanasova** [comment] 2023-10-11 19:28
Multi Combobox Core
<img width="744" alt="Screenshot 2023-10-11 at 3 23 39 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/7adbfa16-89e7-4ca0-b2f1-53bba67e3606">

To reproduce:
- type "test" in the input field
- the error message will appear correctly
- go to the dropdown menu with the keyboard keys and then back to the input field
- add another letter to "test"
- the error message appears for a sec in a popover

https://github.com/SAP/fundamental-ngx/assets/39598672/3ee58813-50b1-44b0-8753-4b72410746ae

**Comment by InnaAtanasova** [comment] 2023-10-11 19:39
Multi Combobox Core in Mobile mode
broken CSS for the error message
<img width="1523" alt="Screenshot 2023-10-11 at 3 38 40 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/5086cba4-88ba-432b-8dcb-e7aaa064e2cc">

**Comment by InnaAtanasova** [comment] 2023-10-11 19:44
Multi Combobox Core in Mobile mode
When an item is selected the input is cleared but the item doesn't change its state in the list. The user might get confused that something went wrong. 
https://github.com/SAP/fundamental-ngx/assets/39598672/c720babd-ba86-4d24-9fef-11e6ca21cc2b

**Comment by InnaAtanasova** [comment] 2023-10-11 19:45
Multi Combobox Core in Mobile mode
very insignificant and actually not reproducible in real mobile mode (size) but in desktop you can see it
<img width="1717" alt="Screenshot 2023-10-11 at 3 40 22 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/b396c5c7-bd58-40fc-9f9c-9afb8284df20">

**Comment by InnaAtanasova** [comment] 2023-10-11 19:48
Multi-Combobox with Groups
using the keyboard to open the dropdown shows an error that disappears 

https://github.com/SAP/fundamental-ngx/assets/39598672/9d6bf481-cfc9-49cc-8f05-ccc493a4bb0f

**Comment by InnaAtanasova** [comment] 2023-10-11 20:06
Multi Input Core

In smaller screens the input should have an indication how many more items are selected but not shown. For example 5 more. In this case there's no way for the user to know how many items are selected until they open the dropdown list
<img width="534" alt="Screenshot 2023-10-11 at 4 04 42 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/8a820bbf-f232-49bf-b66f-b1294a663d19">


UI5 implementation:
<img width="484" alt="Screenshot 2023-10-11 at 4 04 53 PM" src="https://github.com/SAP/fundamental-ngx/assets/39598672/652a4901-5f63-4fe9-8216-a59e21d0c3a9">

**Comment by droshev** [comment] 2023-10-11 21:22
Clustering the findings:

Blockers:
- [ ] Theming **(to be confirmed)**- https://github.com/SAP/fundamental-ngx/issues/10700
- [ ] Theming **(to be confirmed)**- https://github.com/SAP/fundamental-ngx/issues/10628

**Comment by mikerodonnell89** [comment] 2023-10-12 16:22
core multi-combobox - when opening in mobile mode on chrome on an actual phone, URL bar blocks the input and you can't swipe/scroll to see it. **MIKE**

![httpsfundamental-ngx netlify app#coremulti-combobox](https://github.com/SAP/fundamental-ngx/assets/2471874/e559f0c5-31f0-4a10-a541-0698f30258e6)

**Comment by g-cheishvili** [comment] 2023-10-15 15:04
<img width="1151" alt="Screenshot 2023-10-15 at 19 02 54" src="https://github.com/SAP/fundamental-ngx/assets/28543391/1059340c-90dd-4080-9c12-e24461be294d">

Something's terribly wrong with platform thumbnail and I do not know whether we should delete it or fix it

**Comment by N1XUS** [comment] 2023-10-16 06:43
@droshev `Drag and drop does not work on card layout` it's actually working, but the drag area of the card is not obvious. Need to discuss the design and user interaction logic

**Comment by N1XUS** [comment] 2023-10-16 06:44
`After closing/dismissing a dialog, we should be bringing the focus back to the previously focused element. Now it is going back to the start of the page` - checked with Dialog documentation page. Everything works as described. Could someone provide a page where this is happening?

**Comment by N1XUS** [comment] 2023-10-16 12:33
`Core mobile calendar: unnecessary scrollbar:` -> is not a bug. We use size constrains in config of the dialog window:
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/525b6c27-8584-485e-98d0-f4d04204d2b5)

**Comment by N1XUS** [comment] 2023-10-25 14:28
![image](https://github.com/SAP/fundamental-ngx/assets/6586561/bceb0fb1-a9ec-44d9-a496-5749f09a3d1a)
Inline help does not look vertically centered

**Comment by droshev** [comment] 2024-03-02 13:24
@kalo2711 Can you retest the not checked issues and document what is reproducible?

**Comment by kalo2711** [comment] 2024-04-03 18:11
NOT fixed:
- Pagination: when page loading is in progress, I think we should disable pagination buttons in order not to mess up the data.

**Closed** 2024-09-18 18:01 UTC
Labels: Defect Hunting
