### ISSUE TITLE
Fixed Card Layout: There is no ‘Drag & Drop’ functionality provided with the keyboard for the cards as highlighted in red

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3812] opened 2020-11-11 05:23 UTC
Description: There is no ‘Drag & Drop’ functionality provided with the keyboard for the cards as highlighted in red

Expected: Drag & drag functionality which can be achieved by mouse, shall also be available from the keyboard.

Screenshot: 

![image](https://user-images.githubusercontent.com/32538291/98772133-08285300-240c-11eb-8171-749bec6c1373.png)

**Comment by DeepakSap14** [comment] 2020-12-30 08:42
drag drop with keyboard will be handled by application developer. not possible within component.

**Comment by DeepakSap14** [comment] 2021-02-01 06:04
@puru-hk please see my above comment.

Drag and drop through keyboard is Operating system functionality. i have not seen this kind of functionality anywhere implemented within component.
please let me know, if you find any such component where drag&drop has been done by keyboard only.

**Comment by puru-hk** [comment] 2021-03-26 02:26
@Sanjay-1312 Please let us know how do we test this from the keyboard.

**Comment by puru-hk** [comment] 2021-06-04 05:29
@DeepakSap14 accessibility team told us to refer this link (https://wiki.wdf.sap.corp/wiki/display/Acc/Drag+and+Drop) for drag and drop functionality. Please go through and let me know your concern on this.

**Comment by Sanjay-1312** [comment] 2021-06-04 05:57
Hello Colleagues,

 To implement the 'Drag and Drop option you can find the details below.
https://wiki.wdf.sap.corp/wiki/display/Acc/Drag+and+Drop

Thanks and Regards
Sanjay

**Comment by DeepakSap14** [comment] 2021-06-04 09:20
@puru-hk 
this is an enhancement. it won't be a small change and it applies to all components which have drag-and-drop functionality eg: list, grid-list, table, fixed-card-layout, file-uploader.

**Comment by OleksiyDrozdov** [comment] 2021-09-27 14:10
this task looks like a duplicate of  https://github.com/SAP/fundamental-ngx/issues/4612 that I implemented and waiting for review comments. I suggest closing this one (3812)

**Closed** 2021-09-28 13:13 UTC
Labels: enhancement, platform, core, ariba, Medium, ATL
