### ISSUE TITLE
Accessibility_Testing_Feed Input_Core

### ISSUE THREAD

**Issue by Wemitha1234** [SAP/fundamental-ngx#6216] opened 2021-08-03 07:29 UTC
Accessibility: Feed Input-Core Component (There are couple of accessibility issues found while testing, so i have attached error document for you reference.) Screenshot:

[Feed Input_Core_ARIBA Controls.docx](https://github.com/SAP/fundamental-ngx/files/6922123/Feed.Input_Core_ARIBA.Controls.docx)

Issue 1

Priority:	Medium
Checkpoint:	ACC-264

Observed Behavior:
Placeholder “Post something here” is not read out when Feed Input is accessed. 
Extra information “example” is also conveyed. 

Speech output is:
Feed input example 
Feed message edit  
Type in text.

Expected Behavior:
Ideally, placeholder label should be conveyed and only relevant information about the UI should be conveyed.      

Screenshot:
 
![image](https://user-images.githubusercontent.com/88035260/127975506-9d434d43-e7a2-4bfb-9357-cbab71e09a1d.png)

**Comment by puru-hk** [comment] 2021-08-12 08:07
Issue is fixed

**Comment by Sanjay-1312** [comment] 2021-08-12 08:11
Hello Colleagues,

The issue is fixed.
Hence Closing the ticket.

Retest Details:
URL: https://deploy-preview-6292--fundamental-ngx.netlify.app/#/core/feed-input
JAWS 2021

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-08-12 08:11 UTC
Labels: bug, core, ariba, QA Approved, ATL
