### ISSUE TITLE
specific component icons are change when a component uses a regular icon

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-ngx#3365] opened 2020-09-22 16:11 UTC
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
There are many components that use sap-icon class. When the fd-icon is loaded it resets the styling of the icons being used in the other components. In the screenshot you will notice that the shellbar profile icon is not the proper color and placement. Same for the side navigation in the documentation website
#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest
![Screen Shot 2020-09-22 at 12 08 04 PM](https://user-images.githubusercontent.com/50607147/93908469-a598bd80-fccc-11ea-9055-27c62e5b6120.png)

**Comment by salarenko** [comment] 2020-09-24 08:27
@stefanoScalzo 
Could you provide steps to reproduce the issue? I cannot reproduce it in NGX CORE documentation.

**Comment by kavya-b** [comment] 2021-05-25 06:00
@puru-hk @Seamoo13 please verify this, doesn't seem to be reproducible. Could not understand the reproduction steps properly, but this is what I tried:
1. Go to Shellbar component https://sap.github.io/fundamental-ngx/#/core/shellbar and observe the icons
2. Go to Icon component https://sap.github.io/fundamental-ngx/#/core/icon
3. Go to shellbar component again(not back press, go to the link again) and observe the icons
The icons look all same to me.

**Comment by puru-hk** [comment] 2021-05-25 06:10
@stefanoScalzo could you please retest this issue. If you are able to reproduce. Please provide the steps.

**Comment by kavya-b** [comment] 2021-05-25 12:33
Closing this issue as the issue description is insufficient and we were not able to see any breaks due to icon in other components.

**Closed by kavya-b** 2021-05-25 12:33 UTC
Labels: bug
