### ISSUE TITLE
Defect Hunting for Sprint 65 - Bern

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5702] opened 2021-06-17 17:15 UTC
Please report the issues you found during the defect hunting with the following format:

```
- [ ] Short title containing the component name
- Description of the issue
- Ways to reproduce it
- Screenshot or gif
- Browser 
```

Before starting to work on the issue please write your name after the title in bold.
Once the PR is open, please link a link to the PR after your name
Mark this issue as done by checking the checkbox

Example:
<img width="836" alt="Screen Shot 2021-06-03 at 3 29 26 PM" src="https://user-images.githubusercontent.com/39598672/120701160-828bf380-c480-11eb-8aba-d84e08204da8.png">

**Comment by InnaAtanasova** [comment] 2021-06-21 15:58
From previous sprints:
- [ ] https://github.com/SAP/fundamental-ngx/issues/4772
- [ ] https://github.com/SAP/fundamental-ngx/issues/5420
- [ ] https://github.com/SAP/fundamental-ngx/issues/5573

**Comment by mikerodonnell89** [comment] 2021-06-24 16:43
- [ ] Action sheet examples - clicking reject shows the message toast "cancel action" when there's a cancel button, kind of confusing 
- [ ] Date picker - I am wondering if the bound data should not update immediately when the input changes but instead when the user presses enter or the input loses focus, a la time picker.  On ui5 it waits until the blur event
- [ ] Popover scroll bug - open a popover then scroll away from it and click anywhere on the screen, which closes the popover.  Sometimes this will cause the screen to automatically scroll to the (now closed) popover trigger.  This doesn't happen all the time - not sure what the real root cause is
- [ ] Product switch RTL L/R arrow keys going in the wrong direction
- [ ] Slider RTL arrow keys are going in the wrong direction as well
- [ ] Step input - click the plus button - press space bar to "re-click" the button - visually button is pressed but # doesn't increase
- [ ] Time picker - using the keyboard to press the up arrow/down arrow increase/decrease transparent buttons correctly adjusts the time but does not visually indicate the button is being pressed

**Comment by aberikashvili** [comment] 2021-06-29 12:14
Mobile Wizard looks differently when RTL is on.

RTL off:
![image](https://user-images.githubusercontent.com/3863691/123795348-fb9e2f80-d8f4-11eb-952a-f1742f9c7312.png)

RTL on:
![image](https://user-images.githubusercontent.com/3863691/123795388-06f15b00-d8f5-11eb-8932-eb2788655be1.png)

**Comment by aberikashvili** [comment] 2021-06-29 12:16
I think wizard content should have padding left and right 
![image](https://user-images.githubusercontent.com/3863691/123795676-4f107d80-d8f5-11eb-9485-4f858d180013.png)

**Comment by mikerodonnell89** [comment] 2021-06-29 15:12
> I think wizard content should have padding left and right

@aberikashvili I agree this looks a little strange, but we need to give the developer ultimate flexibility to do whatever they want with the wizard content.  Perhaps the example HTML can include a little bit of inline CSS to add some padding

**Comment by mikerodonnell89** [comment] 2021-06-29 15:20
> Mobile Wizard looks differently when RTL is on.

@aberikashvili These problems (RTL and how the next steps overflow the container) are present in fundamental-styles and should be fixed there

**Closed** 2022-07-19 19:20 UTC
Labels: Defect Hunting, denoland, denoland-seville
