### ISSUE TITLE
Choose the version of the documentation

### ISSUE THREAD

**Issue by JohnHavok** [SAP/fundamental-ngx#2503] opened 2020-05-11 10:36 UTC
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
Documentation is only available for the latest version.
If a user is working with an old version, many elements will not be accessible to him or a component may work differently.
e.g Documentation of sapui5
![image](https://user-images.githubusercontent.com/34537974/81552294-8df71300-9383-11ea-9080-3569c2c3682b.png)

**Comment by salarenko** [comment] 2020-05-11 11:01
Duplicate of #1533
Thanks for bringing this, we are aware how important this feature is and we will try to bring it as soon as possible.

**Closed by salarenko** 2020-05-11 11:01 UTC
