### ISSUE TITLE
Stackblitz is not working in Platform

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#5287] opened 2021-05-04 18:04 UTC
#### Is this a bug, enhancement, or feature request?
Stackblitz links are not working. There's no error displayed, just the examples are not rendered in the playground

**Comment by kavya-b** [comment] 2021-05-05 06:58
@InnaAtanasova 
Did some analysis, and it seems like after https://github.com/SAP/fundamental-ngx/pull/4737 was merged, the stackblitz examples started breaking. The PRs before that work fine and the ones after that break stackblitz. 
<img width="360" src="https://user-images.githubusercontent.com/53509521/117105785-5ce5ce80-ad9c-11eb-8aab-c4b65a4148c9.png">

The root cause might be that instead of importing `.ts` , `.html` was imported. 
<img width="869" alt="Screenshot 2021-05-05 at 12 08 59 PM" src="https://user-images.githubusercontent.com/53509521/117105619-0bd5da80-ad9c-11eb-9ad3-d585e68a43f3.png">

I made the changes locally to check but stackblitz still breaks. I suppose only after this change gets merged to main, we can actually verify if netlify is fixed or not, or if this even is the issue. The required changes are already part of PR 5015.

**Comment by dimamarksman** [comment] 2021-05-15 07:03
As far as I understand stackblitz stopped working for any @fundamental-ngx/platform example.
There is an error in the console that `NullInjectorError: No provider for ContentDensityService!`

**Comment by dimamarksman** [comment] 2021-05-15 07:16
I believe `ContentDensityService` should be optional in this case

**Comment by dimamarksman** [comment] 2021-05-18 10:48
The root of the issue is that we have some injection that does not work with ViewEngine properly.
Since Stackblitz uses ViewEngine we see that problem there.

**Closed** 2021-05-18 16:01 UTC
Labels: platform, stackblitz
