### ISSUE TITLE
Bug: Switch: It’s missing switch example with label on/off inside

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3366] opened 2020-09-23 04:16 UTC
Description: It’s missing switch example with label on/off inside:

Expected: Inside switch should add the on/off label

Attached screenshot: 

![image](https://user-images.githubusercontent.com/32538291/93966068-64161a00-fd81-11ea-92b9-007af9689e10.png)

Expected: 

![image](https://user-images.githubusercontent.com/32538291/93966187-ad666980-fd81-11ea-8e6e-1e243657e4a5.png)

**Comment by sKudum** [comment] 2021-05-24 12:36
As per Fiori latest it is obsolete ..text option is not allowed inside switch.

<img width="1074" alt="2021-05-24_15-53-14" src="https://user-images.githubusercontent.com/53487468/119348561-ac902980-bcba-11eb-9c83-eedb43e96d85.png">




Hence its not a bug.

**Comment by puru-hk** [comment] 2021-05-24 12:50
There is a discrepancy between fiori guidelines and fiori visual spec. Hence we are not fixing this issue.

**Comment by kenykim** [comment] 2021-05-24 18:23
missing a label on Switch is not a bug since Visual Core and Fiori guidelines have the pattern. 
doesn't need to fix the issue

**Comment by sKudum** [comment] 2021-05-25 05:23
Hi @puru-hk , as we got confirmation from designer am closing this issue.

**Closed by sKudum** 2021-05-25 05:23 UTC
Labels: Medium, blocked, bug, design-discrepancy, platform, ready for qa
