### ISSUE TITLE
[Sourcing][Dev-blocker][fdp-table] No way to set some rows as selected programmatically by default

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9277] opened 2023-01-25 09:32 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
1) Add a fdp table , selection mode = multiple
2) programatically set some rows as checked 
3) So that user can see those rows as default selected

Not sure , if we can do it as of today. Please update.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 13
core / platform : 0.35.x

#### If this is a bug, please provide steps for reproducing it.
1) Add a fdp table , selection mode = multiple
2) try to set programatically some rows as checked 
3) not able to achieve this

#### Is there anything else we should know?
please update if this can be achieved somehow?

**Comment by mikerodonnell89** [comment] 2023-01-30 21:39
Closing as this is basically a duplicate of #9239 and @platon-rov has solved this with #9304

**Closed by mikerodonnell89** 2023-01-30 21:39 UTC
Labels: enhancement

**Comment by I543348** [comment] 2023-03-06 08:46
This is fixed and tested on https://deploy-preview-9304--fundamental-ngx.netlify.app/#/platform/table
