### ISSUE TITLE
Popover placement and fillControlMode

### ISSUE THREAD

**Issue by salarenko** [SAP/fundamental-ngx#2641] opened 2020-06-08 12:11 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When popover `[placement]` is used together with `[fillControlMode]`, popover is wrongly placed.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v.18

#### If this is a bug, please provide steps for reproducing it.
**Bottom-end**
```
	<fd-popover placement="bottom-end" fillControlMode="at-least">
		<fd-popover-control>
			<button>Some button</button>
		</fd-popover-control>
		<fd-popover-body>
			<span>LONG TEXT OPTION</span>
		</fd-popover-body>
	</fd-popover>
```
Result:
![image](https://user-images.githubusercontent.com/17496353/84028759-97c76280-a991-11ea-9573-a2c1c0328bf3.png)

**Left**

```
	<fd-popover placement="left" fillControlMode="at-least">
```
Result:
![image](https://user-images.githubusercontent.com/17496353/84028840-b88fb800-a991-11ea-8701-085abef79cea.png)

**Comment by droshev** [comment] 2020-12-10 01:26
@salarenko is this still valid?

**Comment by manjunathanagaraj** [comment] 2021-05-18 06:20
@droshev  , is this 'fillControlMode' exposed to developer? I could not find information about this in documentation page. I think this is no more valid as we are now using angular CDK. Can this be closed?

**Comment by dimamarksman** [comment] 2021-08-25 16:04
closing as couldn't reproduce on [this example](https://stackblitz.com/edit/angular-mpd9jl?file=src%2Fapp%2Fpopover-placement-example.component.html)

**Closed by dimamarksman** 2021-08-25 16:04 UTC
Labels: bug, core, denoland, intro
