### ISSUE TITLE
Accessibility Bug: When ‘focus’ is on the complete wrapper reading is made as ‘loading’ and the label ‘use Busy indicator as a block wrapper’ is not conveyed

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3112] opened 2020-08-28 10:31 UTC
Fundamental core component: Busy indicator 

Description: When ‘focus’ is on the complete wrapper reading is made as ‘loading’ and the label ‘use Busy indicator as a block wrapper’ is not conveyed by the screen reader. 

Expected: The labels should get associated with the control when accessed.

Attached the screenshot. 

![image](https://user-images.githubusercontent.com/32538291/91551418-bcefbf80-e947-11ea-886b-b7c270033386.png)

**Comment by Lokanathan-k** [comment] 2021-05-06 06:00
@puru-hk on checking found that whatever defined in the aria-label is readout in the screen reader, this is not a bug and its just a documental changes, does this need a PR to be opened?.

**Comment by Lokanathan-k** [comment] 2021-05-25 11:20
style changes has been  introduced and PR merged in fundamental styles (PR 2339) and its in the version 18 current version is in the 17 so the version has to be bumped up, so putting this issue on hold

**Comment by platon-rov** [comment] 2021-06-18 09:23
Even if loading if false `loading` is read - but it shouldn't

**Closed** 2021-08-10 09:09 UTC
Labels: bug, core, ariba, Medium, Screen Reader, ATL
