### ISSUE TITLE
bug: breadcrumb (core): user is redirected to home page after clicking on specific links 

### ISSUE THREAD

**Issue by nikvalor** [SAP/fundamental-ngx#4840] opened 2021-03-03 14:37 UTC
#### Is this a bug, enhancement, or feature request?
Bug
#### Briefly describe your proposal.
user is redirected to home page after clicking on specific links

#### If this is a bug, please provide steps for reproducing it.
**Steps to reproduce:**
1) Navigate on /core/breadcrumb
2) Click on any breadcrumb link from 'An example using href' section 
3) Observe page
*Video*: https://www.loom.com/share/765923e4b0f34e3d8e3f7a9794bdd655

#### Is there anything else we should know?
Also, error in console is displayed after clicking on the first links 
![image](https://user-images.githubusercontent.com/74654139/109821412-a00daf00-7c3e-11eb-8eb6-6b474bd2a9fe.png)

**Comment by kavya-b** [comment] 2021-06-01 04:04
I think this is a duplicate of #3153 and is being fixed in PR #5517 .
@manu-kr @puru-hk

**Comment by puru-hk** [comment] 2021-06-02 04:26
@nikvalor This is not an issue. We need to check on click on the breadcrumb event trigger is happening. It is up to the application team that on click on the breadcrumb it should navigate to respective page.

**Closed by puru-hk** 2021-06-02 04:26 UTC
Labels: E2E automation, bug, core, low priority
