### ISSUE TITLE
fix:(platform) Object List item component creation as per Fiori3 recommendation.

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-ngx#2848] opened 2020-07-13 03:50 UTC
Is this a bug, enhancement, or feature request?
enhancement

Briefly describe your proposal.
Create the Object List item component as per Fiori3 recommendation.

Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
9

**Comment by manjunathanagaraj** [comment] 2020-10-09 05:53
Duplicate of issue #3290. Therefor closing it.

**Closed by manjunathanagaraj** 2020-10-09 05:53 UTC
