### ISSUE TITLE
Textarea font size too small

### ISSUE THREAD

**Issue by GoodDesignWorks** [SAP/fundamental-ngx#11809] opened 2024-04-24 08:20 UTC
I want to report a Textarea visual bug:
 
the Textarea currently has a smaller text size than 14px. The CSS parameter should be @sapFontSize. Could you update this, please?

**Comment by droshev** [comment] 2024-04-24 09:53
@GoodDesignWorks I have checked in Styles and NGX what font-size we have set for textarea and it is `--sapFontSize`:
<img width="595" alt="Screenshot 2024-04-24 at 05 51 57" src="https://github.com/SAP/fundamental-ngx/assets/4380815/cec1b35c-70b1-4e6b-a103-51496da1d177">
<img width="880" alt="Screenshot 2024-04-24 at 05 51 31" src="https://github.com/SAP/fundamental-ngx/assets/4380815/06076913-70e6-4930-8ef9-3bdd65886547">

The actual [value](https://github.com/SAP/theming-base-content/blob/3f7f0e5a9e77477ea79ba02b79d5732decfa908e/content/Base/baseLib/sap_horizon/css_variables.css#L17) for Horizon is `0.875rem` which is `14px`

**Comment by droshev** [comment] 2024-04-24 11:21
Actually the issue is reported for readonly textarea

**Comment by droshev** [comment] 2024-05-23 01:52
should be fixed in the latest version now

**Closed by droshev** 2024-05-23 01:52 UTC
Labels: design
