### ISSUE TITLE
Bug: Popups or overlays (dialog, popover, menus,etc) are not opening up in IE browser in documentation app

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3631] opened 2020-10-15 10:59 UTC
Description: popups or overlays (dialog, popover, menus,etc) are not opening up in IE browser in documentation app

Expected: Popups or overlays (dialog, popover, menus,etc) should open properly in IE browser

Steps to reproduce:
1. Open this url in IE browser windows machine https://sap.github.io/fundamental-ngx/#/core/dialog
2. Click on the dialogue it is not opening the popup
3. Sometimes when you are in Dialogue document components. Formatted text component is showing. 
4. Refresh the page and dialogue examples it display and nothing will work try to click on the dialogue example .

**Comment by salarenko** [comment] 2020-10-15 11:34
@puru-hk are you sure this is can be reproduced on `v0.22.0`? I tried to play with Popovers and Dialogs and everything works fine. However there are some errors thrown on latest RC versions, so I guess we should check recently introduced changes.

**Comment by puru-hk** [comment] 2020-10-15 11:40
Yes I'm I'm able to reproduce this issue in windows machine IE browser latest.

**Comment by dimamarksman** [comment] 2020-10-15 12:50
It works for me in Windows 10

![image](https://user-images.githubusercontent.com/3263744/96128518-2464cd00-0efe-11eb-9bb4-a35ec286b26b.png)


@puru-hk please put more details about what OS/browser version is.

**Comment by puru-hk** [comment] 2020-10-15 14:38
@dimamarksman 

IE browser version 
![image](https://user-images.githubusercontent.com/32538291/96144082-66533a80-0f21-11eb-939d-a929204ab9a1.png)
OS version 
![image](https://user-images.githubusercontent.com/32538291/96144319-ab776c80-0f21-11eb-9717-bff296e05c11.png)

Attach the video
[Issue 3631.zip](https://github.com/SAP/fundamental-ngx/files/5385572/Issue.3631.zip)

**Comment by puru-hk** [comment] 2020-10-16 07:15
@dimamarksman I'm able to reproduce this issue in netlify url. Could you please check and let me know if you are not able to reproduce.

**Comment by droshev** [comment] 2020-10-16 23:18
I am able to reproduce @puru-hk 's issus on the latest fundamental-ngx and not able to reproduce on version 0.22

**Comment by dimamarksman** [comment] 2020-10-19 08:29
@puru-hk it works for me in the latest netlify  `v 0.23.0-rc.19`

**Comment by salarenko** [comment] 2020-10-19 08:44
@dimamarksman @puru-hk this is a little twisted.

- 0.22.0 Everything works
- `rc.7` -> `rc.8` (bumping focus-trap) breaks IE11 as described in this issue
- `rc.8` -> `rc.17` still broken
- `rc.17` -> `rc.18` fixed, issue cannot be reproduced
- `rc.18` -> ... sill fixed

I'm going to investigate what caused the issue and how it has been fixed recently.

**Comment by salarenko** [comment] 2020-10-19 10:41
Ok, so here is what I found:
- Problem has been caused by Zone.js in `v.0.11` to which we migrated recently
- Issue has been noticed and reported to the authors of the package
- Issue has been fixed with `v.0.11.2` patch release which we migrated to in `rc.18`.

[Link to the issue in Zone.js repo](https://github.com/angular/angular/issues/38669)

**Closed by salarenko** 2020-10-19 10:41 UTC
Labels: 0.23.0, Defect Hunting, High, IE11, bug
