### ISSUE TITLE
fd-popover is out of the document flow (popover scroll down issue)

### ISSUE THREAD

**Issue by blueskymyw** [SAP/fundamental-ngx#10923] opened 2023-11-08 16:18 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Describe your proposal.
The popover is out of the flow. It is not below the icon

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
angular: 15.2.8
fundamental: 0.42.0-rc.27

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
step one: click the icon to open the popover
step two: scroll down the page
#### Please provide relevant source code (if applicable).
 ` <div>
                      Start By
                      <fd-popover
                        fd-table-popover
                        [focusAutoCapture]="true"
                        [focusTrapped]="true"
                        [(isOpen)]="open[i]"
                      >
                        <fd-popover-control>
                          <div fd-table-inner>
                            <fd-icon
                              fd-table-icon
                              [glyph]="
                                ascending2[i] === false ? 'sort-descending' : 'sort-ascending'
                              "
                            ></fd-icon>
                          </div>
                        </fd-popover-control>
                        <fd-popover-body>
                          <ul fd-list [compact]="true">
                            <li fd-list-item (click)="sortColumn1(true, i)">
                              <i fd-list-icon [glyph]="'sort-ascending'"></i>
                              <span fd-list-title>Sort Ascending</span>
                            </li>
                            <li fd-list-item (click)="sortColumn1(false, i)">
                              <i fd-list-icon [glyph]="'sort-descending'"></i>
                              <span fd-list-title>Sort Descending</span>
                            </li>
                            <li fd-list-item>
                              <i fd-list-icon [glyph]="'filter'"></i>
                              <div
                                fd-form-item
                                [horizontal]="true"
                                (click)="$event.stopPropagation()"
                              >
                                <label fd-form-label for="input-1">Filter</label>
                                <input
                                  fd-form-control
                                  fdCompact
                                  id="input-1"
                                  (keyup)="inputKeyup($event)"
                                  [(ngModel)]="filterVal2"
                                  style="min-width: 164px"
                                />
                              </div>
                            </li>
                          </ul>
                        </fd-popover-body>
                      </fd-popover>
                    </div>`

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
I clicked the icon in yellow but the popover was below the second icon when I scrolled down the page
<img width="292" alt="popover scroll down issue" src="https://github.com/SAP/fundamental-ngx/assets/117795601/fdedd854-8580-48d2-bc31-0764c5b1869d">

**Comment by droshev** [comment] 2024-03-02 15:32
@blueskymyw  I was not able to reproducible here https://fundamental-ngx.netlify.app/#/platform/table/basic. Can you create a stackblitz using the latest version?
![Uploading Screenshot 2024-03-02 at 10.31.23.png…]()

**Comment by droshev** [comment] 2024-05-22 19:50
@blueskymyw closing the ticket since we didn't get any update. Please, report a new ticket if you can create a stackblitz with the issue.

**Closed by droshev** 2024-05-22 19:50 UTC
