### ISSUE TITLE
Bug: Platform Approval Flow Phase 2 defect hunting issues

### ISSUE THREAD

**Issue by kavya-b** [SAP/fundamental-ngx#4734] opened 2021-02-22 06:27 UTC
#### Is this a bug, enhancement, or feature request?
bug
#### Briefly describe your proposal.
1. Spec shows radio buttons in list of approvers: 
<img width="250" alt="Screenshot 2021-02-22 at 11 17 19 AM" src="https://user-images.githubusercontent.com/53509521/108668165-adb98b00-7500-11eb-843b-28fd4e251945.png">
ngx implemented checkboxes for individuals and radio buttons for teams:
<img width="200" alt="Screenshot 2021-02-22 at 11 15 58 AM" src="https://user-images.githubusercontent.com/53509521/108668180-b4e09900-7500-11eb-8b70-5618af01e2b6.png">
was this intended?

2. in RTL mode, the user avatar/image has extra margin:
LTR: <img width="352" alt="Screenshot 2021-02-22 at 10 48 12 AM" src="https://user-images.githubusercontent.com/53509521/108668175-b316d580-7500-11eb-8d25-cb370ce0e322.png">
RTL:<img width="569" alt="Screenshot 2021-02-22 at 10 48 31 AM" src="https://user-images.githubusercontent.com/53509521/108668178-b4480280-7500-11eb-9733-34bcf1925418.png">

3. The texts for `Edit` and `Delete` are actually `Edit approver` and `Remove` according to specs:
<img width="258" alt="Screenshot 2021-02-22 at 11 13 21 AM" src="https://user-images.githubusercontent.com/53509521/108668179-b4e09900-7500-11eb-9e82-efbdb9535b0e.png">

4. Also, some nodes do not show `Edit` in the overflow menu, why is that so?
![image](https://user-images.githubusercontent.com/53509521/108668889-0178a400-7502-11eb-947f-0d6723683fbf.png)

5. The watchers list on editing, does not show `18 more` etc. message when the cursor goes out of focus:
![2021-02-22_11-47-31 (1)](https://user-images.githubusercontent.com/53509521/108670045-3259d880-7504-11eb-9ed6-90d01c7dd5f2.gif)

6. Adding an invalid date throws error on the console and does not let us `Add` approver, but do we need a more graceful way of showing user they entered an invalid date?
![image](https://user-images.githubusercontent.com/53509521/108670233-8cf33480-7504-11eb-90ea-cac547ed9775.png)

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
latest

#### If this is a bug, please provide steps for reproducing it.
described above

**Comment by IlyaSurmay** [comment] 2021-02-22 13:30
> 1. Spec shows radio buttons in list of approvers:
> 
> <img alt="Screenshot 2021-02-22 at 11 17 19 AM" width="250" src="https://user-images.githubusercontent.com/53509521/108668165-adb98b00-7500-11eb-843b-28fd4e251945.png">
> 
> ngx implemented checkboxes for individuals and radio buttons for teams:
> <img alt="Screenshot 2021-02-22 at 11 15 58 AM" width="200" src="https://user-images.githubusercontent.com/53509521/108668180-b4e09900-7500-11eb-8b70-5618af01e2b6.png">
> 
> was this intended?

Yes, this is intended behavior which was discussed during one of the meetings. Checkboxes allow selecting multiple users as approvers and radio buttons allow selecting only one team as an approval team.

> 4. Also, some nodes do not show `Edit` in the overflow menu, why is that so?
>    ![image](https://user-images.githubusercontent.com/53509521/108668889-0178a400-7502-11eb-947f-0d6723683fbf.png)

Editing is allowed only for `not started` nodes.

**Comment by kavya-b** [comment] 2021-02-22 13:58
> > 1. Spec shows radio buttons in list of approvers:
> > 
> > <img alt="Screenshot 2021-02-22 at 11 17 19 AM" width="250" src="https://user-images.githubusercontent.com/53509521/108668165-adb98b00-7500-11eb-843b-28fd4e251945.png">
> > ngx implemented checkboxes for individuals and radio buttons for teams:
> > <img alt="Screenshot 2021-02-22 at 11 15 58 AM" width="200" src="https://user-images.githubusercontent.com/53509521/108668180-b4e09900-7500-11eb-8b70-5618af01e2b6.png">
> > was this intended?
> 
> Yes, this is intended behavior which was discussed during one of the meetings. Checkboxes allow selecting multiple users as approvers and radio buttons allow selecting only one team as an approval team.
> 
> > 1. Also, some nodes do not show `Edit` in the overflow menu, why is that so?
> >    ![image](https://user-images.githubusercontent.com/53509521/108668889-0178a400-7502-11eb-947f-0d6723683fbf.png)
> 
> Editing is allowed only for `not started` nodes.

okay, thank you for clarifying!

**Comment by IlyaSurmay** [comment] 2021-02-23 13:42
> 5. The watchers list on editing, does not show `18 more` etc. message when the cursor goes out of focus:
>   ![2021-02-22_11-47-31 (1)](https://user-images.githubusercontent.com/53509521/108670045-3259d880-7504-11eb-9ed6-90d01c7dd5f2.gif)

This is how multi-input component works in `compact` mode, you can check it by opening StackBlitz example here https://sap.github.io/fundamental-ngx/#/core/multi-input#compactMultiInput
If this is an issue it should be fixed for multi-input, not approval flow

**Closed** 2021-02-24 12:30 UTC
Labels: Defect Hunting, Medium, bug, platform
