### ISSUE TITLE
[Sourcing] ACC-271.1(Level A) Fdp-table toolbar buttons no visible focus issue

### ISSUE THREAD

**Issue by devika-devanand** [SAP/fundamental-ngx#11464] opened 2024-02-26 14:27 UTC
#### Is this a bug, enhancement, or feature request?
Accessibility bug

#### Describe your proposal.
On accessing the ‘Search’, ‘Refresh’, ‘Sort’, ‘Filters’, ‘Settings’ buttons within ‘Q&A’ tab, there is no visible focus provided for all these UI elements.
However all UI elements which are interactive should have a clean 4 sided focus which is clearly visible on all elements to the users.

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx version : 0.43.11

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
Create a fdp-table with the search,sort and filterable functionalities that are accesible fromt he toolbar.
Navigate through the toolbar buttons using the keyboard and check for the focus.
<img width="497" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/1363a957-a4e8-4b66-b10b-8e06f3944c26">

#### Please provide relevant source code (if applicable).
Add columns with the sort and filter functionality along with the search functionality of the fdp-table
<img width="401" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/71935676/80ad05a1-2e31-4c93-8a4b-db0572087edf">

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
All UI elements which are interactive should have a clean 4 sided focus which is clearly visible on all elements to the users.

**Comment by droshev** [comment] 2024-03-05 11:45
@devika-devanand do you think you can provide a stackblitz example as i was not able to reproduce your issue using our example
![table-toolbar-focus](https://github.com/SAP/fundamental-ngx/assets/4380815/acd1fb8f-7134-4020-8269-a779c11d4316)

**Comment by droshev** [comment] 2024-05-22 22:30
@devika-devanand any update?

**Comment by droshev** [comment] 2024-06-11 11:22
@devika-devanand the ticket will be closed if there is no further updates

**Comment by droshev** [comment] 2024-09-19 18:43
no activities => closing the issue

**Closed by droshev** 2024-09-19 18:43 UTC
