### ISSUE TITLE
[P1][Sourcing][Accessibility][ATL Testing][Vertical Navigation][a11y input]Wrong state of the list item read for child nodes

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#10551] opened 2023-09-14 17:12 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Based on ATL testing and verification - in [Vertical Navigation](https://ng-15-downport--fundamental-ngx.netlify.app/#/core/vertical-navigation) accessing the child list items additional information "Closed" is being read for all the child items which is still creating confusion same as the information "collapsed".

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
`0.43.9`

**Comment by droshev** [comment] 2023-09-14 19:27
@I543348 We were not able to reproduce the issue. We don't hear Closed in the children at all. You will get a link with the recording.

**Closed by droshev** 2023-09-14 19:27 UTC

**Comment by droshev** [comment] 2023-09-14 19:33
<img width="395" alt="Screenshot 2023-09-14 at 3 33 39 PM" src="https://github.com/SAP/fundamental-ngx/assets/4380815/7408fc74-1170-4953-b1d0-7be00982df8f">

**Comment by sagar7259** [comment] 2023-09-20 03:40
Hello,
The issue is no more reproducible, on accessing the children the "Closed" information is no more being read. Hence this ticket can be closed.

Regards,
Sagar (ATL Team)
