### ISSUE TITLE
Size of the popover box shrunks after the scrolling the page down and up again.

### ISSUE THREAD

**Issue by wangwanlin** [SAP/fundamental-ngx#10593] opened 2023-09-25 06:56 UTC
#### Is this a bug, enhancement, or feature request?
Enhancement
#### Briefly describe your proposal.
Size of the popover box shrunks after the scrolling the page down and up again.
<img width="1687" alt="image" src="https://github.com/SAP/fundamental-ngx/assets/13607996/568c0353-673a-4dcc-9c0e-ebbe481fe3d2">

**Comment by skaquib123** [comment] 2023-09-26 05:14
Hi @wangwanlin ,  I can't reproduce this issue. Is it possible for you share a stackblitz link or a video of how you are using the component. It will help me understand the problem and also may I know which version of fundamental you are using?

**Comment by wangwanlin** [comment] 2023-09-26 07:19
https://github.com/SAP/fundamental-ngx/assets/13607996/cc3de701-f80b-4ec1-87b4-06458de51d4d

**Comment by mikerodonnell89** [comment] 2023-10-03 17:36
fixed by https://github.com/SAP/fundamental-ngx/pull/10631

**Closed by mikerodonnell89** 2023-10-03 17:36 UTC
