### ISSUE TITLE
Accessibility:List: The tooltip “Title1” provided for buttons, does not convey meaningful information about the UI

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3477] opened 2020-09-30 05:47 UTC
Description: The tooltip “Title1” provided for buttons, does not convey meaningful information about the UI

Expected: Tooltip/text alternative provided for UI should be meaningful and should define purpose of UI. 

Screenshot

![image](https://user-images.githubusercontent.com/32538291/94647606-73abda80-030e-11eb-8e7c-e5587b5fc056.png)

**Comment by sKudum** [comment] 2020-12-16 07:20
Duplicate of #3485 , hence closing it.

**Closed by sKudum** 2020-12-16 07:20 UTC
Labels: Medium, Screen Reader, accessibility, bug, platform
