### ISSUE TITLE
Table (platform): multi-select table borders no aligned

### ISSUE THREAD

**Issue by Seamoo13** [SAP/fundamental-ngx#4410] opened 2021-01-20 10:02 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.
1. missing bottom border for first multi-select checkbox
2. checkbox borders and table borders aren't aligned

#### If this is a bug, please provide steps for reproducing it.
1. go to https://fundamental-ngx.netlify.app/#/platform/table
2. scroll to the 'Multiple Row Selection' example
3. look at the borders for checkboxes and table

*Actual results:*
1. first row's checkbox is missing a border line
2. checkbox and table border lines aren't aligned
![2021-01-20_4](https://user-images.githubusercontent.com/47522152/105159033-4bdbbf00-5b17-11eb-837a-0d85a08975b3.png)

*Expected results:* should match designs
![2021-01-20_5](https://user-images.githubusercontent.com/47522152/105159037-4e3e1900-5b17-11eb-93d4-4a3602894e1c.png)

**Comment by dimamarksman** [comment] 2021-01-21 08:57
That's because of fundamental-styles issue https://github.com/SAP/fundamental-styles/issues/1948.
It should be fixed once we moved to the new table layout (when frozen columns will be rendered in a dedicated table)

**Comment by platon-rov** [comment] 2021-05-24 12:27
Can not reproduce. Should be closed.

**Closed** 2021-05-24 12:41 UTC
Labels: Testing (QA), bug, platform, table

**Comment by nikvalor** [comment] 2021-05-25 08:07
Fixed
