### ISSUE TITLE
Accessibility:Step Input: The label “PC” is not read when step input field is accessed. 

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3489] opened 2020-09-30 06:19 UTC
Description: The label “PC” is not read when step input field is accessed. 

Expected: corresponding label should be read out when UI is accessed. 

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/94649784-02225b00-0313-11eb-893f-3438612d7b0f.png)

**Comment by puru-hk** [comment] 2021-02-24 07:00
@Sanjay-1312 could you please retest this issue

**Comment by Sanjay-1312** [comment] 2021-02-24 07:19
Hello Colleagues,

The issue is fixed and hence Closing the ticket.

Thanks and Regards
Sanjay

**Closed** 2021-02-24 07:22 UTC
Labels: Screen Reader, accessibility, bug, low priority, platform
