### ISSUE TITLE
Full name is not seen on hover in multi-input.

### ISSUE THREAD

**Issue by AlpanaSamanta** [SAP/fundamental-ngx#10849] opened 2023-10-31 08:17 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Describe your proposal.
if any value in the multi-input is long, when we hover on it, we do not see the full name in tooltip

#### Can you handle that on the application side
NO

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
fundamental-ngx = 0.46.1
angular = 16.2.8

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
We use Multi- Input component

#### Please provide relevant source code (if applicable).
<label fd-label for="dropdownExampleInput1">Default Multi Input</label>
<fd-multi-input
  inputId="dropdownExampleInput1"
  [dropdownValues]="[
    'SomeLongTextToShowThatWidthWillGrowWithTheContentSomeLongTextToShowThatWidthWillGrowWithTheContentSomeLongTextToShowThatWidthWillGrowWithTheContent',
    'Banana',
    'Pineapple',
    'Tomato',
    'Kiwi',
    'Strawberry',
    'Blueberry',
    'Orange'
  ]"
  placeholder="Search here..."
  [(ngModel)]="selected"
  style="width: 200px"
></fd-multi-input>

#### Please provide stackblitz example(s).
https://stackblitz.com/edit/aipjbn?file=src%2Fapp%2Fmulti-input-dropdown-width-example.component.html

#### In case this is Accessibility related topic, did you consult with an accessibility expert? If not, please do so and share their recommendations. 
No

#### Did you check the documentation and the API?
Yes

#### Did you search for similar issues?
Yes

#### Is there anything else we should know?
No

**Comment by droshev** [comment] 2023-11-07 20:35
Actually we should wrap the text on multiple lines

**Comment by skaquib123** [comment] 2023-11-20 09:28
Hello @droshev, Should we word-wrap list item text? Is that what you are referring to?

**Comment by droshev** [comment] 2023-12-19 17:04
maybe duplicate of https://github.com/SAP/fundamental-ngx/issues/11025?

**Comment by rajeev-9bit** [comment] 2023-12-20 12:30
Hi team, please review this proposed fix: https://github.com/SAP/fundamental-ngx/pull/11121

**Closed** 2024-01-02 15:57 UTC
Labels: bug
