### ISSUE TITLE
Accessibility Bug: The aria-selected attribute is not allowed on this A.

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#3154] opened 2020-08-30 05:20 UTC
Fundamental core component: "Pagination"

Description: The aria-selected attribute is not allowed on this A.

Code Snippet:

(<a aria-selected="false" class="fd-pagination__link ng-star-inserted" role="button" tabindex="0">1</a>)
![image](https://user-images.githubusercontent.com/32538291/91651801-b0d24200-eaae-11ea-99dd-94257f66145c.png)

Expected: Developers must use valid markup and follow the rules of the ARIA specification

Screenshot:

![image](https://user-images.githubusercontent.com/32538291/91651787-7f597680-eaae-11ea-9f53-0e6149fd3ec2.png)

**Comment by Sanjay-1312** [comment] 2021-05-27 06:09
![P N A](https://user-images.githubusercontent.com/78714518/119774692-2d7c3a80-bee0-11eb-9fa4-91f46315259c.png)

Fundamental core component: "Pagination"

Description: The aria-selected attribute is not allowed on this A.

Code Snippet:

(1)
image

Expected: Developers must use valid markup and follow the rules of the ARIA specification

**Comment by manu-kr** [comment] 2021-05-27 08:52
@Sanjay-1312 The URL you're verifying seems wrong, Please use the below URL for testing this defect.

https://deploy-preview-5468--fundamental-ngx.netlify.app/#/core/pagination

Issue is we shouldn't use aria-selected with <a> tag, so currently we are using 'aria-current' instead of 'aria-select' and it will read selected page current page.

For more information please refer below links.
https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination.
https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

**Comment by Sanjay-1312** [comment] 2021-05-31 08:25
Hello Colleagues,

The issue is fixed.
Hence closing the ticket.

URL: https://deploy-preview-5468--fundamental-ngx.netlify.app/#/core/pagination

Thanks and Regards
Sanjay

**Closed by Sanjay-1312** 2021-05-31 08:25 UTC
Labels: ATL, Medium, bug, core
