### ISSUE TITLE
Popover: As per the RTL mode UI is not proper

### ISSUE THREAD

**Issue by puru-hk** [SAP/fundamental-ngx#5616] opened 2021-06-07 07:38 UTC
#### Is this a bug, enhancement, or feature request?
It is a Bug.

#### Briefly describe your proposal.

UI is not as per the RTL mode

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

30.1

#### If this is a bug, please provide steps for reproducing it.

Login to Fundamental ngx
Select the core
Select the Popover component
Enable RTL button
Click on the Popovers in Dailogs example 
UI is not as per the RTL mode

Expected: UI should be as per the RTL.

Screenshot:

![image.png](https://images.zenhubusercontent.com/5f4c9866d9d21de4c96444ff/0de6ef6e-0989-4546-962c-b60ce1d70283)

**Comment by N1XUS** [comment] 2021-07-16 12:22
Duplicate of #5792

**Closed by N1XUS** 2021-07-16 12:22 UTC
Labels: bug, core, denoland-porto
