### ISSUE TITLE
List Component Bug

### ISSUE THREAD

**Issue by Lokanathan-k** [SAP/fundamental-ngx#5945] opened 2021-07-13 05:26 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Briefly describe your proposal.

list component focusing on the list body instead of list item on tabbing.
<img width="1131" alt="Screenshot 2021-07-13 at 10 53 55 AM" src="https://user-images.githubusercontent.com/53534379/125395348-b4ba3a80-e3c8-11eb-829b-6c16c9691176.png">

**Comment by sKudum** [comment] 2021-07-13 05:38
same issue is raised in https://github.com/SAP/fundamental-ngx/issues/5779 as well. We can close it as it is duplicate of it.

**Closed** 2021-07-13 07:19 UTC
Labels: 0.31, Defect Hunting, High, QA Approved, ariba, bug
