### ISSUE TITLE
Vertical scroll bar disappears when the dialog pops up

### ISSUE THREAD

**Issue by Anysysjgw** [SAP/fundamental-ngx#10697] opened 2023-10-11 03:31 UTC
#### Is this a bug, enhancement, or feature request?
bug

#### Which versions of Angular and Fundamental Library for Angular are affected? Please, specify the exact version. (If this is a feature request, use current version.)
"@angular/core": "15.2.9",
"@fundamental-ngx/core": "0.43.11", (so is in "0.43.6")

#### If this is a bug, please provide steps for reproducing it; the exact components you are using;
As demoed in my attached video,
- the 1st part shows in upgrade branch, the vertical scroll bar of the page disappears every time we pop up a dialog,
- while the 2nd part shows its current behavior before upgrading.
It is a little wired because the whole screen shakes as the vertical scroll bar disappears (when dialog pops up) and appears (when dialog is closed).

https://github.com/SAP/fundamental-ngx/assets/1304168/874beee5-50e1-4a22-8672-003d1ef8dbf4

#### Please provide relevant source code (if applicable).
```typescript
  import { DialogService } from '@fundamental-ngx/core';

  constructor(private dialogService: DialogService) {
    super();
  }

  openDialog(): void {
    this.dialogService.open(CustomizedDialogComponent, {
      backdropClickCloseable: false,
      focusTrapped: true
    });
  }
```

#### Did you check the documentation and the API?
Yes, but didn't find relevant attributes to handle it.

#### Did you search for similar issues?
Yes, but not found.

#### Is there anything else we should know?
This behavior makes users feel wired, and could cause a concern for some users.

**Comment by mikerodonnell89** [comment] 2023-10-11 11:57
I think we'll need to see more of your template code as I'm unable to reproduce this on any browser

**Comment by Anysysjgw** [comment] 2023-10-11 15:41
> I think we'll need to see more of your template code as I'm unable to reproduce this on any browser

Hi Mike, thanks for your reply! As for how to reproduce this issue, it's quite simple (just as the code snippet I put above) because you only need to pop up a dialog on a web page that has a vertical scroll bar, and you will see this issue.

**Comment by mikerodonnell89** [comment] 2023-10-12 17:13
> > I think we'll need to see more of your template code as I'm unable to reproduce this on any browser
> 
> Hi Mike, thanks for your reply! As for how to reproduce this issue, it's quite simple (just as the code snippet I put above) because you only need to pop up a dialog on a web page that has a vertical scroll bar, and you will see this issue.

Our documentation page for the dialog has scrollbars and does not see this issue:

https://github.com/SAP/fundamental-ngx/assets/2471874/f9b3d841-1197-4fd3-86e2-9d427b4a358b

You can also see it is not reproducible on this stackblitz: https://stackblitz.com/edit/7ngzpy?file=src%2Fapp%2Fcomponent-based-dialog-example.component.ts

**Comment by skaquib123** [comment] 2023-10-16 05:24
Hello @Anysysjgw , I do not see any functional dependency in this issue and as Mike as said it is not reproducible either. So I am closing this issue.

**Closed by skaquib123** 2023-10-16 05:24 UTC

**Comment by Anysysjgw** [comment] 2023-10-17 16:04
Hi @mikerodonnell89 @skaquib123 , thanks a lot for your response! I will check how to make this issue reproducible.
By the way, the ngx version in the sampe code of @mikerodonnell89 (https://stackblitz.com/edit/7ngzpy?file=src%2Fapp%2Fcomponent-based-dialog-example.component.ts) seems to be the latest one instead of `0.43.11` in which I find the issue. Could you please have a double check in `0.43.11` as well?

**Comment by joseserrano15** [comment] 2025-01-23 19:32
> Hi [@mikerodonnell89](https://github.com/mikerodonnell89) [@skaquib123](https://github.com/skaquib123) , thanks a lot for your response! I will check how to make this issue reproducible. By the way, the ngx version in the sampe code of [@mikerodonnell89](https://github.com/mikerodonnell89) (https://stackblitz.com/edit/7ngzpy?file=src%2Fapp%2Fcomponent-based-dialog-example.component.ts) seems to be the latest one instead of `0.43.11` in which I find the issue. Could you please have a double check in `0.43.11` as well?

@Anysysjgw I have the same problem. Did you find a solution?
