### ISSUE TITLE
error TS2307: Cannot find module '@ng-bootstrap/ng-bootstrap'

### ISSUE THREAD

**Issue by kushwahashiv** [SAP/fundamental-ngx#984] opened 2019-06-26 22:29 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
After steps mentioned on page https://sap.github.io/fundamental-ngx/home

when I try to restart i.e. `ng serve` to take `angular.json` changes into effect I get the following error. 

```ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                                 
Date: 2019-06-26T22:21:24.212Z
Hash: 1caa2642958f01955a5c
Time: 5429ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 284 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 1.87 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 93.1 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 964 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in node_modules/fundamental-ngx/lib/modal/modal.component.d.ts(1,26): error TS2307: Cannot find module '@ng-bootstrap/ng-bootstrap'.
node_modules/fundamental-ngx/lib/modal/modal.service.d.ts(1,26): error TS2307: Cannot find module '@ng-bootstrap/ng-bootstrap'.

ℹ ｢wdm｣: Failed to compile.
```

#### Which versions of Angular and Fundamental NGX are affected? (If this is a feature request, use current version.)
from `package.json`
 "@angular-devkit/build-optimizer": "0.13.8",
   "@angular/animations": "7.2.14",
    "@angular/cdk": "5.2.1",
    "@angular/common": "7.2.14",
    "@angular/compiler": "7.2.14",
    "@angular/core": "7.2.14",
    "@angular/flex-layout": "7.0.0-beta.24",
    "@angular/forms": "7.2.14",
    "@angular/http": "7.2.14",
    "@angular/platform-browser": "7.2.14",
    "@angular/platform-browser-dynamic": "7.2.14",
    "@angular/router": "7.2.0",
    "fundamental-ngx": "^1.0.0",
#### If this is a bug, please provide steps for reproducing it.
Yes create an angular app and use steps mentioned in https://sap.github.io/fundamental-ngx/home and try to use`table` component

#### Please provide relevant source code if applicable.
I am just using the table sample code mentioned in https://sap.github.io/fundamental-ngx/home

**Comment by MattL75** [comment] 2019-06-26 22:33
Fundamental-ngx is currently on 0.6.0, we haven't reached 1.0.0 yet. Our old versions (dating back to 0.0.27-beta, I believe) did depend on ng-bootstrap. However, that is no longer the case. Can you try running fundamental-ngx 0.6.0 and also install fundamental-styles and update back here?

**Comment by kushwahashiv** [comment] 2019-06-26 22:40
I just followed the steps mentioned in https://sap.github.io/fundamental-ngx/home and I got 
![image](https://user-images.githubusercontent.com/4386810/60219715-60b37c00-9828-11e9-95bb-67f78f876b71.png). Let me try that `0.6.0`

**Comment by kushwahashiv** [comment] 2019-06-26 22:41
yes when I fix to ` "fundamental-ngx": "0.6.0"` in `package.json` that issue goes away but it should have not caused any issue by default installation itself.

**Comment by MattL75** [comment] 2019-06-26 22:44
I'm not sure what would cause that. We ran fresh installs ourselves and it worked fine. If you try to install it fresh now, does it still install 1.0.0? Because if so, I'd be interested to investigate the cause.

**Comment by kushwahashiv** [comment] 2019-06-26 23:20
I verified what you are saying in https://stackblitz.com/edit/angular-ohfasy?file=package.json and it seems work as expected but when you create a sample using angular/cli in your local machine it does works as expected. please see screenshot below
![image](https://user-images.githubusercontent.com/4386810/60221368-3ebcf800-982e-11e9-8cd1-ea29010d20cd.png)

**Comment by droshev** [comment] 2019-06-27 03:11
@kushwahashiv can you try installing and adding `fundamental-ngx` from scratch? It should point to our latest `0.6.0`
As @MattL75 our current version is `0.6.0`. Version `0.1.0` is quite old

**Comment by MattL75** [comment] 2019-06-27 13:46
@droshev He already said that he followed the instructions and that it installed 1.0.0, which I suppose gets somehow coerced to 0.1.0 since 1.0.0 does not exist. I tried it locally and it did install 0.6.0 however, so not sure where the issue lies.

**Comment by kushwahashiv** [comment] 2019-06-27 17:10
I can reproduce that in an actual application we are building here my colleagues as well also in fresh ng cli app as the screenshot shows above too. Not sure what's different in your environment.

**Comment by droshev** [comment] 2019-06-28 12:53
@kushwahashiv could you list the right steps so we can investigate more?

**Comment by droshev** [comment] 2019-08-25 21:42
@kushwahashiv any update?

**Comment by droshev** [comment] 2019-10-26 01:07
@kushwahashiv It has been a while since the issue was open so i will close it. If you need, feel free to open it again

**Closed by droshev** 2019-10-26 01:07 UTC
Labels: question
