### ISSUE TITLE
Bug: Bar - if title is used as first control, then left/right padding should be 1rem

### ISSUE THREAD

**Issue by pierrom** [SAP/fundamental-ngx#5625] opened 2021-06-08 01:07 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
Visual Core - says if title is used as first control, then left/right padding should be 1rem.
<img width="998" alt="Bar Design SubHeader" src="https://user-images.githubusercontent.com/71797052/121106274-8f7b5080-c7ba-11eb-8ded-f59a51e34a97.png">
<img width="834" alt="Visual Core" src="https://user-images.githubusercontent.com/71797052/121106290-96a25e80-c7ba-11eb-89bf-50cd6284c4ef.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
v30.1 r61

#### If this is a bug, please provide steps for reproducing it.
Go to https://fundamental-ngx.netlify.app/#/core/bar
Scroll down to Bar Design SubHeader and Bar Design with title and SubHeader

**Comment by sKudum** [comment] 2021-06-24 07:42
Can be closed its duplicate of #5681.

**Comment by Seamoo13** [comment] 2021-06-24 07:51
is a duplicate, closing issue.

**Closed by Seamoo13** 2021-06-24 07:51 UTC
Labels: 0.30, bug, core, design_team, ready for qa
