### ISSUE TITLE
[Sourcing][a11y help][ariaLabel][P4] is not getting recognised for fd components

### ISSUE THREAD

**Issue by Vijaya-Bharathi-Reddy** [SAP/fundamental-ngx#10426] opened 2023-08-30 09:36 UTC
#### Is this a bug, enhancement, or feature request?

Bug

#### Briefly describe your proposal.

When [ariaLabel] is added to the fd components, it is not getting applied to multi-input component.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

Angular - 15.2.0
Fundamental-ngx - 0.43.0-rc.16 

#### If this is a bug, please provide steps for reproducing it.

1. Go to Multi Input fd component
2. Go the html file of it and try passing the [ariaLabel] to the fd component and check if it is getting added to the actual component or not.

#### Please provide relevant source code if applicable.

![image](https://github.com/SAP/fundamental-ngx/assets/143493234/c8686918-3a5d-4c7a-b265-6a296ef679ab)

![image](https://github.com/SAP/fundamental-ngx/assets/143493234/6b1145d5-0374-449a-afe0-2a40641d7ec4)

Please find below the stackblitz source code link for multi-input-example.component.html, where the ariaLabel is being added but not recognised by the multi-input component.

https://stackblitz.com/edit/angular-buzpyi?file=src%2Fapp%2Fmulti-input-example.component.ts,src%2Fapp%2Fmulti-input-example.component.html

#### Is there anything else we should know?

This bug is causing an issue in accessibility testing.

**Comment by I543348** [comment] 2023-08-31 06:33
duplicate of https://github.com/SAP/fundamental-ngx/issues/10393

**Closed** 2023-09-13 22:51 UTC

**Comment by sagar7259** [comment] 2023-10-13 08:33
Hello Team,

Now the label and UI type of a 'Multi value input' is read correctly. hence This ticket can be closed.

Regards,
Sagar
