### ISSUE TITLE
FormGroup Problem while using ng-templates

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental-ngx#3933] opened 2020-11-25 10:04 UTC
#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
When we use structured layout like this where fields are part of the content of fdp-form-group

```html
<fdp-form-group>
    <fdp-form-field></fdp-form-field>
    <fdp-form-field></fdp-form-field>
    <fdp-form-field></fdp-form-field>
   ...
```

All works. But as soon as you use this structure with ng-templates
https://gist.github.com/fkolar/e18ab9ca7223dd9e96d04ce9675c92ed

I have found two problems:
 - Injection of `@Optional() private formGroupContainer: FormGroupContainer`  stop working as parent component is the same for both FormGroup and FormField (so I added extra binding to pass the parent)
 - It renders double labels. as shown on the picture

<img width="1607" alt="Screen Shot 2020-11-25 at 10 54 17 AM" src="https://user-images.githubusercontent.com/17149942/100211569-958b9d00-2f0c-11eb-81e3-644e8e351654.png">

The `xx` I just added to the label spam to make sure its coming from the same source. 

Those additional fields are outside of the fdp-form-group section parts

<img width="1207" alt="Screen Shot 2020-11-25 at 11 05 51 AM" src="https://user-images.githubusercontent.com/17149942/100212957-49415c80-2f0e-11eb-9699-e509ad1c0380.png">

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)

```
Angular CLI: 10.2.0
Node: 12.0.0
OS: darwin x64

Angular: 10.2.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.6
@angular-devkit/build-angular      0.1002.0
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               10.2.0
@angular-devkit/schematics         10.1.6
@angular/cdk                       10.2.7
@angular/cli                       10.2.0
@schematics/angular                10.1.7
@schematics/update                 0.1002.0
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         3.9.7
    
```

**Comment by fkolar** [comment] 2020-11-25 10:13
Looks like the problem is wiht 
`[forceRender]="true"`

Which was in original version but we dont need it anymore, so the fix should be remove forceRender bindings

**Comment by dimamarksman** [comment] 2021-03-09 19:16
@fkolar is it still actual? I don't see `forceRender` option anymore

**Comment by droshev** [comment] 2021-06-12 11:35
@fkolar closing the issue as it is old. feel free to reopen it if the issue is still valid

**Closed by droshev** 2021-06-12 11:35 UTC
Labels: ariba, platform
