### ISSUE TITLE
[Sourcing]fdp-table Drag and Drop : should work before / after / inside a row node

### ISSUE THREAD

**Issue by I543348** [SAP/fundamental-ngx#9466] opened 2023-03-01 15:55 UTC
#### Is this a bug, enhancement, or feature request?
Enhancement request

#### Briefly describe your proposal.
User should be able to pick up a row and can choose to drop either inside a parent node , or before a row or after a row.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Angular 15
core / plaform: 0.38.2

#### Is there anything else we should know?
This is needed for guided sourcing customer commitment

**Comment by mikerodonnell89** [comment] 2023-03-02 14:41
Duplicate of #9421

**Closed by mikerodonnell89** 2023-03-02 14:41 UTC
