### ISSUE TITLE
Combobox Control should be able to display an icon with the text

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-ngx#1131] opened 2019-08-15 20:00 UTC
#### Is this a bug, enhancement, or feature request?
Enhancement

#### Briefly describe your proposal.
[Combobox](https://sap.github.io/fundamental-ngx/combobox) component has an option to provide an itemTemplate to the component which allows customizable popover list (with icons, for example). Once the user selects a list item with an icon, the icon and the text value should appear in the combobox control. 

<img width="1709" alt="Screen Shot 2019-08-15 at 3 59 12 PM" src="https://user-images.githubusercontent.com/39598672/63122869-b88f7900-bf75-11e9-9935-e467fbdfa3c4.png">
<img width="1704" alt="Screen Shot 2019-08-15 at 3 59 20 PM" src="https://user-images.githubusercontent.com/39598672/63122874-ba593c80-bf75-11e9-9563-c62263bf0921.png">

**Comment by MattL75** [comment] 2019-08-15 20:16
This is solved by adding the possibility to pass a template for the trigger. I propose to close this and track the issue only in #1129.

**Comment by sKudum** [comment] 2019-08-26 04:45
Assigning it to Lokanathan, as he was not able to assign it to himself.

**Comment by sKudum** [comment] 2019-08-26 04:55
Duplicate of 1129, therefore closing it.

**Closed by sKudum** 2019-08-26 04:55 UTC
